#!/usr/bin/env python3
"""Embeds tools/courses.js into index.html between /*COURSES:START*/ and /*COURSES:END*/ marker comments.
Run again after editing tools/courses.js.   python3 tools/embed_courses.py"""
import os, re, sys
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
idx = os.path.join(ROOT, 'index.html')
src = open(idx, encoding='utf-8').read()
js = open(os.path.join(ROOT, 'tools', 'courses.js'), encoding='utf-8').read()
if '</script' in js.lower(): sys.exit('source contains </script')
block = '/*COURSES:START (generated by tools/embed_courses.py, edit tools/courses.js instead)*/\n' + js.rstrip() + '\n/*COURSES:END*/\n'
if '/*COURSES:START' in src:
    src = re.sub(r'/\*COURSES:START.*?/\*COURSES:END\*/\n', lambda m: block, src, count=1, flags=re.S)
else:
    anchor = '/*INTRO:START'
    if src.count(anchor) != 1: sys.exit('anchor not found exactly once')
    src = src.replace(anchor, block + anchor, 1)
open(idx, 'w', encoding='utf-8').write(src)
print('embedded', len(block), 'bytes')
