// Embeds tools/accounts_ui.js into index.html as the Accountant page (replaces the old openAccountantSheet the first time,
// then replaces the block between its markers). Usage: node tools/embed_accounts_ui.js
const fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..'), file = path.join(root, 'app.js');
let s = fs.readFileSync(file, 'utf8');
const src = fs.readFileSync(path.join(__dirname, 'accounts_ui.js'), 'utf8').replace(/\s+$/, '\n');
const START = '/*ACCTUI:START (generated by tools/embed_accounts_ui.js from tools/accounts_ui.js, edit that file instead)*/\n';
const END = '/*ACCTUI:END*/\n';
const block = START + src + END;
const a = s.indexOf('/*ACCTUI:START'), b = s.indexOf(END);
if (a >= 0 && b > a) { s = s.slice(0, a) + block + s.slice(b + END.length); console.log('replaced the existing block'); }
else {
  const i = s.indexOf('function openAccountantSheet(){');
  const j = s.indexOf('/** One simple "which period?" step');
  if (i < 0 || j < i) throw new Error('could not find the old openAccountantSheet');
  s = s.slice(0, i) + block + s.slice(j); console.log('replaced the old openAccountantSheet');
}
fs.writeFileSync(file, s);
