T = {}
T['anxiety'] = dict(
 doc=["Anxiety is not a modern invention. The Bible meets it head on, and its answer is deeper than \"just stop worrying.\" The Greek word Jesus and Paul use, merimnao, comes from two ideas: to divide, and the mind. Anxiety is a divided mind, pulled in different directions by things that have not happened yet. That is why Jesus says, \"Take no thought for your life\" (Matthew 6:25): He is not telling you to stop caring, He is telling you not to let your mind be torn into pieces.",
 "The doctrine underneath is the Fatherhood and providence of God. Jesus does not argue from willpower; He argues from the character of the Father. If He feeds the birds and clothes the grass, and you are worth far more than they are, then your worry is a quiet verdict that you do not believe He is that kind of Father (Matthew 6:26-32). Anxiety is therefore more than a feeling: it is a question about who is in charge. Providence means that God governs all things for the good of those who love Him (Romans 8:28), and that no sparrow falls without Him.",
 "Paul gives the practice: \"in every thing by prayer and supplication with thanksgiving let your requests be made known unto God\" (Philippians 4:6). Notice the order. You name the thing (requests), you hand it over (prayer), and you remember who He has been (thanksgiving). The result is not always a changed situation. It is a guard: the peace of God \"shall keep your hearts and minds.\" The word for keep is a military word, a garrison posted at the gate. Peace does not remove the battle; it stands guard inside you while the battle goes on.",
 "Peter adds the verb: \"casting all your care upon him\" (1 Peter 5:7). To cast is to throw something onto another's back, the way you would throw a cloak over a donkey. You are not asked to hold the care more gently; you are asked to throw it, and let Him carry it, \"for he careth for you.\""],
 christ="Revealed in Christ: Jesus is the one who slept in the stern of a boat in a storm (Mark 4:38). The Son of God was not anxious, because He knew the Father. In Gethsemane He felt real agony (Luke 22:44), so He is not a distant teacher but a High Priest who can be touched with the feeling of our infirmities (Hebrews 4:15). He took anxiety to the Father in prayer, and He teaches you to do the same.",
 word="The word behind the word: \"Be careful for nothing\" in the older English means \"do not be full of care.\" The Greek is me merimnate: stop being pulled apart. The remedy Paul offers is the opposite of division, a single-minded turning of everything toward God.",
 walk="Walk it out: Write the worry down in one sentence. Under it write, \"Lord, I give You this.\" Then write three things God has already done for you. Do it again tonight, and again tomorrow. Anxiety loses ground when it is named, handed over and answered with thanks.",
 key=['Matthew 6:25-27','Matthew 6:33-34','Psalms 55:22','Isaiah 26:3','1 Peter 5:6-7'],
 prayers=[("Father, calm my divided mind","Father in heaven, You see the thoughts that run through my mind tonight. I come to You because I cannot hold them together by myself. I confess that I have tried to carry what You never asked me to carry, and that I have trusted my own planning more than Your promises.\n\nLord, I cast every care on You right now, one by one. I name them before You: my money, my family, my health, my future, the things I cannot control. I throw them on You, because You care for me. I take them back no more.\n\nThank You that You are my Father, that You feed the birds and clothe the grass, and that I am worth more to You than they are. Thank You for every time You have carried me before. Let Your peace, which passes all understanding, stand guard over my heart and my mind in Christ Jesus. Teach me to seek first Your kingdom, and trust that You will add what I need. Today is enough. Tomorrow belongs to You. In Jesus' name, Amen."),("When the storm is loud","Lord Jesus, You slept in the boat while the waves beat over it, and when Your disciples woke You, You spoke and there was a great calm. There is a storm in my heart. Speak to it now. Say to my fear, \"Peace, be still.\"\n\nI refuse to let fear have the last word. I choose to trust the One who rules the winds and the sea. Hold me. Hold my family. Put a guard around my thoughts, and bring to my mind everything true, honorable, right and pure. Where I cannot see the way, be the way. Thank You that You are with me in the boat. Amen.")],
 declare=["I will not be anxious about anything. I bring everything to God in prayer with thanksgiving.","The peace of God guards my heart and my mind in Christ Jesus.","My Father knows what I need before I ask.","I cast every care on the Lord, for He cares for me."])
T['fear'] = dict(
 doc=["Fear is the first emotion recorded after the fall: \"I was afraid... and I hid\" (Genesis 3:10). From that moment, fear and hiding have gone together. The Bible's answer to fear is not to be fearless in ourselves but to know who is with us. The most repeated command in Scripture, in one form or another, is \"Fear not,\" and it is almost always followed by \"for I am with thee.\" Courage in the Bible is never a personal trait; it is the fruit of presence.",
 "Isaiah 41:10 stacks the promises: \"I am with thee... I am thy God... I will strengthen thee... I will help thee... I will uphold thee with the right hand of my righteousness.\" The right hand in Scripture is the hand of power and covenant. God does not say the water will not come; He says that when you pass through the waters, He will be with you (Isaiah 43:2). The doctrine is that of the covenant presence of God: He binds Himself to His people and walks into the fire with them, as the fourth figure in Nebuchadnezzar's furnace (Daniel 3:25).",
 "Paul writes to Timothy, who was timid: \"God hath not given us the spirit of fear; but of power, and of love, and of a sound mind\" (2 Timothy 1:7). The word for fear here is deilia, cowardice, a shrinking back. It does not come from God. What He gives instead has three parts: power to act, love to give, and a sound mind, a self-controlled, steady way of thinking. Fear shrinks the mind; the Spirit steadies it.",
 "John goes deepest: \"There is no fear in love; but perfect love casteth out fear: because fear hath torment\" (1 John 4:18). The cure for fear is to be convinced of being loved. The more you know the Father's love, the less room there is for dread. And there is a holy fear, the fear of the Lord, which is reverence and which actually frees us from every other fear (Proverbs 14:26)."],
 christ="Revealed in Christ: At the lowest point of fear, Jesus said to a frightened man, \"Fear not; I am the first and the last: I am he that liveth, and was dead; and, behold, I am alive for evermore\" (Revelation 1:17-18). The risen Christ holds the keys of death and the grave. Whatever you fear ends at a door He has the key to.",
 word="The word behind the word: The Hebrew al tira, \"do not fear,\" is a command in the form of a gift. It is often spoken together with \"I am with you\" in the same breath. The comfort is never \"nothing bad will happen\" but \"you will not face it alone.\"",
 walk="Walk it out: Write down the thing you fear most. Beside it write, \"God is with me in this.\" Read Isaiah 41:10 aloud three times, putting your own name in it. Then take one small step you have been avoiding. Courage grows by doing the next right thing in His presence.",
 key=['Isaiah 41:10','Isaiah 43:1-2','Psalms 23:4','Psalms 27:1','Joshua 1:9','2 Timothy 1:7'],
 prayers=[("Lord, You are with me","Father, You are my light and my salvation; whom shall I fear? You are the strength of my life; of whom shall I be afraid? I bring my fear to You. I name it: (say it aloud). It feels bigger than I am. But You are bigger than it.\n\nLord, You said, \"Fear not, for I am with thee; be not dismayed, for I am thy God.\" I take You at Your word. Strengthen me, help me, uphold me with Your righteous right hand. Where I have been hiding, call me out, as You called Adam: \"Where art thou?\" I come out of hiding. I come to You.\n\nFill me with Your perfect love, which casts out fear. Give me power to act, love to give and a sound mind to think. Let me walk through the valley of the shadow of death and fear no evil, for You are with me; Your rod and Your staff comfort me. In Jesus' name, Amen."),("Courage for today","Lord, be strong and courageous in me today. I do not feel brave, but I choose to obey. Courage is not the absence of fear, it is taking the next step while You hold my hand, and so I take it.\n\nGo before me into every room, every conversation, every decision. Be on my right hand and my left, and behind me. Be my shield, my fortress and my very present help in trouble. Where I have to speak, give me words. Where I have to wait, give me peace. Where I have to walk away, give me strength.\n\nThank You that You have not given me the spirit of fear, but of power, love and a sound mind. Thank You that You hold my right hand and say to me, Fear not, I will help thee. I am not alone, and I will not be put to shame. In Jesus' name, Amen.")],
 declare=["The Lord is my light and my salvation; whom shall I fear?","God has not given me a spirit of fear, but of power, love and a sound mind.","Perfect love casts out fear, and I am loved by God.","I will be strong and courageous, for the Lord my God is with me wherever I go."])
T['grief'] = dict(
 doc=["Grief is love with nowhere to go, and the Bible gives it room. The Psalms contain more laments than praises. Job sat with his friends for seven days in silence. Jesus, who knew He would raise Lazarus in minutes, still stood at the tomb and wept (John 11:35). The shortest verse in the Bible is the longest comfort for the grieving: the Son of God is not embarrassed by tears.",
 "The doctrine here is the compassion of God and the hope of the resurrection. \"The Lord is nigh unto them that are of a broken heart; and saveth such as be of a contrite spirit\" (Psalm 34:18). The Hebrew for nigh means near, within reach. He does not wait for you to finish grieving before drawing close. And Paul writes that we do not sorrow \"as others which have no hope\" (1 Thessalonians 4:13). Christians grieve fully, but with hope: for those who die in Christ, death is a sleep before the morning of the resurrection, and we will be reunited with them.",
 "Jesus promised, \"Blessed are they that mourn: for they shall be comforted\" (Matthew 5:4). The word for comfort comes from parakaleo, to call alongside. It is the root of the title Paraclete, given to the Holy Spirit. God's comfort is a Person who comes alongside, not a slogan. Paul calls Him \"the God of all comfort, who comforteth us in all our tribulation, that we may be able to comfort them which are in any trouble\" (2 Corinthians 1:3-4). Your grief, held in His hand, will one day make you a comforter to someone else.",
 "At the end of the story, \"God shall wipe away all tears from their eyes; and there shall be no more death, neither sorrow, nor crying, neither shall there be any more pain\" (Revelation 21:4). Notice that God Himself does the wiping. The tears are real, and the hand that wipes them is real too."],
 christ="Revealed in Christ: Isaiah calls Him \"a man of sorrows, and acquainted with grief\" (Isaiah 53:3). Jesus did not only watch human sorrow; He entered it and carried it to the cross, and then He rose. Because He rose, every grave in Christ is a temporary address.",
 word="The word behind the word: The Hebrew word often translated \"comfort,\" nacham, also means to sigh, to breathe deeply, to be sorry together with someone. God's comfort begins with sitting beside you and sighing with you.",
 walk="Walk it out: Do not rush your grief. Write a letter to the one you lost, or say their name aloud and thank God for one specific gift they gave you. Reach out to one person today and tell them honestly how you are. Grief shared is grief halved.",
 key=['Psalms 34:18','Psalms 147:3','Matthew 5:4','John 11:25-26','1 Thessalonians 4:13-14','Revelation 21:4'],
 prayers=[("In the valley of loss","Father of mercies and God of all comfort, my heart is heavy and the pain is real. I miss them so much. I thank You that You are near to the brokenhearted, and that You do not despise my tears. You keep count of my sorrows and put my tears in Your bottle.\n\nLord Jesus, You wept at Lazarus's grave, and so I know that You understand. Weep with me now. Hold me when I cannot hold myself. Let me cry without shame and rest without guilt.\n\nThank You for the gift of the one I lost, and for every memory. Thank You for the hope of the resurrection: that You are the resurrection and the life, and that those who die in You will live. Give me strength for today only. Surround me with people who love me. Holy Spirit, my Comforter, come alongside me. Heal my broken heart and bind up my wounds. One day You will wipe away every tear. Until then, carry me. In Jesus' name, Amen."),("When the pain comes back","Lord, the grief came back like a wave tonight. It caught me when I was not ready, and I am tired of being strong. I do not need answers; I need You. Be near.\n\nYou collect my tears in Your bottle and You count them. Nothing I am feeling is a surprise to You or a failure before You. Thank You that Jesus wept at a grave, so I may weep too without shame. Remind me that this ache is love with nowhere to go, and that love is never wasted. Hold the memories that hurt and the ones that heal.\n\nI believe that You are making all things new, and that You will wipe away every tear. Until that day, carry me. Let Your peace settle on my heart, give me sleep tonight, and bring me gently to the morning. Send a kind person to sit with me when I need it. In Jesus' name, Amen.")],
 declare=["The Lord is near to the brokenhearted, and He saves the crushed in spirit.","I do not grieve as those who have no hope.","Jesus is the resurrection and the life, and in Him I will live.","God will wipe away every tear from my eyes."])
T['depression'] = dict(
 doc=["Depression is not a sign of weak faith. Some of the Bible's greatest people wrote and prayed from the pit: David, Elijah under the juniper tree wanting to die (1 Kings 19:4), Jeremiah, Job, and the sons of Korah in Psalm 42. The Bible treats the downcast soul with tenderness and honesty, and it never tells the sufferer to snap out of it. It models a conversation with your own soul.",
 "In Psalm 42:5 the writer talks to himself: \"Why art thou cast down, O my soul? and why art thou disquieted in me? hope thou in God: for I shall yet praise him.\" The words cast down come from a Hebrew verb meaning bowed low. The psalmist does not pretend the feeling is absent. He questions it, and then he speaks to it, directing his soul toward God. Hope in Hebrew, yachal, means to wait, to expect with patience. Hope is not a mood; it is an act of waiting on a faithful God.",
 "The doctrine is God's tender care for the weak. When Elijah despaired, God did not rebuke him; He sent an angel with food and let him sleep (1 Kings 19:5-8), and then spoke to him in a still small voice. God deals with the whole person, body and soul. That is why it is wise, and not unfaithful, to seek rest, food, daylight, friends and medical help alongside prayer.",
 "Isaiah 42:3 says of the Messiah: \"A bruised reed shall he not break, and the smoking flax shall he not quench.\" You may feel like a bent reed or a smoldering wick. He does not snap you or snuff you out. And Isaiah 61:3 promises \"the garment of praise for the spirit of heaviness.\" Praise is not denial of pain; it is a garment we put on when we cannot feel anything else."],
 christ="Revealed in Christ: Jesus said, \"My soul is exceeding sorrowful, even unto death\" (Matthew 26:38). He knows the weight on the soul. And He brought light into the darkest day: the cross, and then the third morning. No darkness is final in Him.",
 word="The word behind the word: The Hebrew nefesh, translated \"soul,\" means the whole living self, your breath, your appetite, your life. When the psalmist speaks to his soul, he speaks to his whole self and calls it back to God.",
 walk="Walk it out: Do one small thing today: open a window, take a short walk, call one person, eat a proper meal. Then pray one honest sentence, even \"God, I am here.\" If the heaviness lasts for weeks, please see a doctor or counselor; asking for help is not a lack of faith.",
 key=['Psalms 42:5','Psalms 42:11','Psalms 40:1-2','Isaiah 42:3','Isaiah 61:3','Lamentations 3:21-23'],
 prayers=[("When my soul is cast down","Lord, my soul is bowed low and I do not have the words. I come to You as I am. You know the heaviness I carry. You do not condemn me for it. You are near to the brokenhearted and You save those who are crushed in spirit.\n\nI speak to my own soul now, as the psalmist did: Why are you cast down, O my soul? Hope in God, for I shall yet praise Him. Even if I cannot feel it, I choose to wait on You. Lift me out of the pit, set my feet on a rock and put a new song in my mouth.\n\nSend me what I need: rest, light, kind people, wise help. Give me courage to ask for it, from friends, from my pastor and from a doctor if I need one. Give me the garment of praise in place of the spirit of heaviness. Thank You that You will not break a bruised reed or quench a smoking wick. Hold me through this night, and bring me to the morning. In Jesus' name, Amen."),("A small prayer for a hard day","God, I do not have strength to pray long, so I will just come. Be with me in this heaviness. You said You are near to the brokenhearted and save those of a contrite spirit. I am here, and I need You near.\n\nDo for me what I cannot do for myself. Lift the weight a little. Help me get up, wash, eat something, open the curtains, send one message to one safe person. Help me take the next small step, and the one after, and let that be enough for today.\n\nSilence the voice that says I am a burden and that nothing will change. Speak truth over it: that I am loved, that this season is not forever, that You are with me in the pit. Send the right people, and the right help. If I am in danger, give me courage to tell someone and to call for help at once. Thank You that Your mercies are new every morning, and that great is Your faithfulness. In Jesus' name, Amen.")],
 declare=["The Lord is near to me, and He will not leave me in the pit.","I will hope in God, for I shall yet praise Him.","He will not break the bruised reed or quench the smoking flax.","His mercies are new every morning."])
T['loneliness'] = dict(
 doc=["The first thing God called \"not good\" in all creation was loneliness: \"It is not good that the man should be alone\" (Genesis 2:18). We were made for fellowship, with God and with each other. Loneliness is a real pain, and the Bible does not shame it. But it also reveals the deepest answer: you are never actually alone, because God is with you.",
 "The doctrine is the omnipresence and the covenant faithfulness of God. David asks, \"Whither shall I go from thy spirit? or whither shall I flee from thy presence?\" (Psalm 139:7), and answers that even in the uttermost parts of the sea, God's hand leads him. And Hebrews 13:5 quotes the promise with a force that English hides: in the Greek there are five negatives piled up, something like \"I will never, never, no never leave you, no never forsake you.\" It is among the strongest promises in the New Testament.",
 "God also sets the lonely in families: \"God setteth the solitary in families\" (Psalm 68:6). The church is meant to be that family, a place where the fatherless, widows and strangers belong. Loneliness is often answered by God through people, so we are called both to receive and to become that answer for others.",
 "Even Jesus knew loneliness. On the night He was betrayed, His friends fell asleep, and at the cross He cried, \"My God, my God, why hast thou forsaken me?\" (Matthew 27:46). He was forsaken so that you would never be. And after His resurrection His last words to His disciples were, \"Lo, I am with you alway, even unto the end of the world\" (Matthew 28:20)."],
 christ="Revealed in Christ: His very name is Emmanuel, \"God with us\" (Matthew 1:23). The whole Gospel is the story of God refusing to stay away. He came to where you are.",
 word="The word behind the word: In the promise \"I will never leave thee,\" the Hebrew raphah means to let go, to drop, to slacken the grip. God says, \"I will never loosen My hold on you.\"",
 walk="Walk it out: Today, reach out to one person: send a message, make a short call, or visit someone. Pray: \"Lord, show me who needs a friend.\" Join one gathering of believers this week, even if you only sit at the back. Connection often starts with one small step toward someone else.",
 key=['Genesis 2:18','Psalms 68:6','Psalms 139:7-10','Deuteronomy 31:8','Hebrews 13:5','Matthew 28:20'],
 prayers=[("You are with me","Father, I feel alone tonight. The house is quiet and the silence is loud. But Your Word says You are near, and I take You at Your Word. You will never leave me nor forsake me. You are closer than my own breath. Come into this room and let me feel Your presence.\n\nForgive me where loneliness has made me bitter, or made me hide. Heal the hurts that make it hard to trust. Lord, You set the solitary in families. Place me in a family of believers who will welcome me, and teach me to welcome others. Send me a friend. Make me a friend.\n\nI thank You that Jesus was forsaken so that I will never be. Let that truth sink from my head to my heart. Fill the empty space in me with Your love. Lead me into the day with a quiet courage. In Jesus' name, Amen."),("For the lonely around me","Lord, open my eyes to the lonely people near me: the widow, the stranger, the one who sits alone at the back, the neighbour whose door never opens. You set the solitary in families, and You are the Father of the fatherless. Use me to be part of how You do it.\n\nTake me out of my own heaviness and my own shyness. Give me the courage to greet, to call, to visit, to invite someone to a meal. Give me the right word and the patience to listen without hurrying. Let no one leave my company feeling smaller than they came.\n\nWhere I am lonely myself, meet me, and lead me to people who will walk with me. Make our homes and our churches places where no one is forgotten. Use me to be Your hands and Your voice today, and let someone know through me that they are seen, loved and not forgotten. In Jesus' name, Amen.")],
 declare=["The Lord will never leave me nor forsake me.","God is with me always, to the end of the age.","I am a member of God's family, and I belong.","In His presence there is fullness of joy."])
T['anger'] = dict(
 doc=["Anger itself is not a sin. God is often described as angry at injustice and evil, and Jesus was angry in the temple. Paul commands, \"Be ye angry, and sin not: let not the sun go down upon your wrath\" (Ephesians 4:26). The word he uses for the second kind of anger, parorgismos, means a simmering, provoked state, anger that is nursed. The command is to feel it honestly, and then to deal with it quickly before it turns into bitterness.",
 "The doctrine of the human heart is clear: James says that \"the wrath of man worketh not the righteousness of God\" (James 1:20). Our anger usually defends our own comfort, pride or rights, not God's righteousness. Proverbs adds that \"a soft answer turneth away wrath\" (Proverbs 15:1), and that the one who rules his spirit is better than one who takes a city (Proverbs 16:32). Self-control is a form of strength, and the Holy Spirit grows it in us.",
 "Under much anger there is hurt, fear or injustice. God wants us to bring all three to Him. Romans 12:19 says, \"Vengeance is mine; I will repay, saith the Lord.\" Handing a wrong over to God is not weakness. It is trusting that the Judge of all the earth will do right (Genesis 18:25), and it frees us from carrying the weight of revenge.",
 "Forgiveness finishes what self-control starts. \"Be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you\" (Ephesians 4:32). The anger that is surrendered becomes mercy, and that is a work that only the Spirit can do."],
 christ="Revealed in Christ: \"When he was reviled, reviled not again; when he suffered, he threatened not; but committed himself to him that judgeth righteously\" (1 Peter 2:23). Jesus shows us the way of handing anger over to the Father.",
 word="The word behind the word: \"Slow to anger\" in Hebrew is erek appayim, literally \"long of nostrils.\" The picture is of a person who breathes slowly while the fire rises. It is the exact description God gives of Himself (Exodus 34:6).",
 walk="Walk it out: When you feel anger rising, stop, breathe slowly and pray one sentence: \"Lord, give me Your heart for this.\" Before bed, name what you are angry about and hand it to Him. If you need to, speak to the person privately and kindly. Do not let the sun set on it.",
 key=['Ephesians 4:26-27','Ephesians 4:31-32','James 1:19-20','Proverbs 15:1','Proverbs 16:32','Romans 12:19'],
 prayers=[("Lord, take my anger","Father, I am angry, and You know exactly why. I do not hide it from You. Thank You that You are slow to anger and rich in mercy. Forgive me for the angry words and thoughts that have come from my heart, and for the times I have let the sun go down on my wrath.\n\nI hand over to You the one who hurt me. I hand over my right to get even. You are the righteous Judge, and You will do right. Heal the wound underneath my anger: the hurt, the fear, the sense of being unseen.\n\nGive me a soft answer. Make me quick to listen, slow to speak and slow to become angry. Fill me with Your Spirit of self-control. Teach me to forgive as You have forgiven me. Where I need to make peace, show me the first step. Soften my heart, and let Your peace rule in it. In Jesus' name, Amen."),("In the heat of the moment","Lord, I am about to lose my temper. Stop me. Put a guard on my lips and keep watch at the door of my mouth. Let me breathe once, and breathe Your name. Slow my heart. Slow my words.\n\nShow me what is under the anger: hurt, fear, tiredness, pride, a need that was not met. I give You the thing under the thing. Give me a soft answer, since a soft answer turns away wrath. Let me be swift to hear, slow to speak and slow to wrath, for the anger of man does not work the righteousness of God.\n\nIf I have already spoken harshly, give me the humility to go back and say sorry. Let this moment be a place where Your peace wins, and where the person in front of me sees something of Jesus. Cleanse me and cool me. In Jesus' name, Amen.")],
 declare=["I am slow to anger and quick to listen.","The Spirit of God gives me self-control.","I leave vengeance to the Lord, and I choose forgiveness.","A soft answer turns away wrath."])
T['forgiveness'] = dict(
 doc=["Forgiveness is at the center of the Gospel. The Greek word aphiemi, to forgive, means to send away, to release. In Christ our sins are sent away as far as the east is from the west (Psalm 103:12). Forgiveness is not forgetting, and it is not pretending that wrong did not happen. It is canceling a debt: you decide that the one who owes you will not be made to pay.",
 "The doctrine is grace. Paul writes, \"forgiving one another, if any man have a quarrel against any: even as Christ forgave you, so also do ye\" (Colossians 3:13). The word forgiving here is charizomai, from charis, grace. To forgive is to give graciously. We forgive because we have been forgiven: the measure of our mercy is not the size of the offense but the size of the debt we were released from. In Jesus' parable of the unforgiving servant (Matthew 18:21-35), the servant who was forgiven ten thousand talents refused to forgive a hundred pence. The point is that we have been forgiven an unpayable debt.",
 "Jesus ties receiving and giving closely together: \"If ye forgive men their trespasses, your heavenly Father will also forgive you\" (Matthew 6:14). This does not mean we earn forgiveness by forgiving. It means that a heart that clings to bitterness has not really understood grace. Forgiveness is also a decision before it is a feeling: you choose it, and the feelings follow in time.",
 "Forgiving does not always mean reconciling. Reconciliation needs repentance and trust, which take two people. Forgiveness takes one. And it does not mean staying in danger: you can forgive an abuser and still protect yourself and others. You hand the debt over to God, who judges justly."],
 christ="Revealed in Christ: From the cross He prayed, \"Father, forgive them; for they know not what they do\" (Luke 23:34). He forgave while the nails were still in. The cross is the place where justice and mercy meet.",
 word="The word behind the word: In Hebrew, the word for forgive, salach, is used only of God. Only He truly cancels sin. When we forgive one another, we reflect His image.",
 walk="Walk it out: Write the name of the person you need to forgive. Say aloud, \"I release you from what you owe me, and I give the matter to God.\" Pray for their good, even if it is short and hard. Repeat it every time the memory returns, until the sting fades.",
 key=['Colossians 3:13','Ephesians 4:32','Matthew 6:14-15','Matthew 18:21-22','Psalms 103:10-12','Luke 23:34'],
 prayers=[("To forgive from the heart","Father, thank You that You have forgiven me everything in Christ. I could never pay the debt, and You paid it for me. Now I choose to forgive (name the person). They hurt me. What they did was wrong, and it cost me. But I cancel the debt. I release them to You, and I trust You to judge justly.\n\nI ask You to heal the places where I was wounded. Take away bitterness, and keep it from taking root in me. Where I feel I cannot forgive, I ask for Your help, because I cannot do this in my own strength. Bless them. Do them good. Let me see them as You see them.\n\nIf I have wronged someone, show me, and give me courage to ask for forgiveness. Wash me clean and free me from guilt. Let my life show the grace that has been shown to me. In Jesus' name, Amen."),("Lord, forgive me","Father, I have sinned against You and against others. I do not excuse it, blame anyone, or make it smaller than it is. I name it before You, because You already see it, and You are faithful and just to forgive.\n\nHave mercy on me according to Your steadfast love. Wash me thoroughly from my iniquity and cleanse me from my sin. Create in me a clean heart and renew a right spirit within me. Restore to me the joy of Your salvation and uphold me with a willing spirit. Where my sin harmed someone, show me what to say and what to repair, and give me the courage to do it.\n\nThank You that where sin abounded, grace abounded much more. Thank You that You cast my sins into the depths of the sea and remember them no more. Let me not carry what You have already carried. Teach me to walk in the freedom of the forgiven, and to forgive others as I have been forgiven. In Jesus' name, Amen.")],
 declare=["I am forgiven, because Jesus paid for my sin.","I forgive as I have been forgiven.","Bitterness has no place in my heart.","God's grace in me is greater than any wrong done to me."])
T['guilt'] = dict(
 doc=["Guilt has two faces. There is true guilt, the conviction of the Holy Spirit that we have done wrong, which is a gift because it leads us to repent. And there is false guilt and shame, the whispering accusation that says, \"You are beyond forgiveness,\" which is a lie. The Gospel answers both: for true guilt, a full pardon; for false guilt, a loud \"No condemnation!\"",
 "Paul's triumphant statement is Romans 8:1: \"There is therefore now no condemnation to them which are in Christ Jesus.\" The Greek begins with ouden, absolutely none, and the word condemnation, katakrima, is a court word: the sentence of a judge. It is gone. The believer has been tried, the verdict has been delivered and the penalty has been paid by Christ, who \"hath made him to be sin for us, who knew no sin; that we might be made the righteousness of God in him\" (2 Corinthians 5:21). That is called justification, being declared righteous on Christ's account, not on ours.",
 "True conviction works differently from condemnation. Conviction is specific (\"this thing\"), it leads to confession and cleansing (1 John 1:9), and it ends with relief. Condemnation is vague (\"you are bad\"), it makes you hide, and it ends with despair. The Spirit convicts to draw you home; the accuser condemns to push you away. \"The accuser of our brethren is cast down\" (Revelation 12:10), and he has been overcome \"by the blood of the Lamb.\"",
 "God does more than forgive; He forgets in the sense that He will not hold it against you: \"their sins and iniquities will I remember no more\" (Hebrews 8:12). When you confess, the case is closed. You may remember your sin; He does not count it."],
 christ="Revealed in Christ: At the cross, Jesus took the legal charges against us, \"blotting out the handwriting of ordinances that was against us... nailing it to his cross\" (Colossians 2:14). Every charge, every accusation, every record of debt is pinned to a cross, and the cross is empty because He is risen.",
 word="The word behind the word: The Hebrew for atonement, kaphar, means to cover, to wipe away. The blood of the sacrifice did not just hide sin; it cleansed. In Christ the covering is complete.",
 walk="Walk it out: Take a piece of paper. Write what you feel guilty about, and under it write 1 John 1:9 in your own words. Confess it plainly. Then tear the paper up. When the accusation returns, answer it with Romans 8:1 aloud.",
 key=['Romans 8:1','1 John 1:9','Psalms 103:12','Isaiah 1:18','Hebrews 10:22','Colossians 2:13-14'],
 prayers=[("Free from condemnation","Father, I come to You carrying guilt. Some of it is real, because I have sinned. Some of it is a heavy shame that does not seem to go away. I bring it all to You. Search me, and show me what is truly mine to confess.\n\nI confess my sin plainly: (say it). I do not make excuses. I thank You that You are faithful and just to forgive me and to cleanse me from all unrighteousness. By the blood of Jesus, I am forgiven.\n\nI reject the accuser's voice. Jesus took my punishment, and there is no condemnation for me. I am not what I did. I am Your child, justified, accepted and loved. Free me from shame and from the habit of punishing myself. Help me to forgive myself as You have forgiven me, and teach me to walk in newness of life. In Jesus' name, Amen."),("When the accuser speaks","Lord Jesus, the accuser is telling me I am finished, that I have done too much, that God has had enough. I bring those words to the light. You are my advocate with the Father, and You are the propitiation for my sins. If I confess my sin, You are faithful and just to forgive me and to cleanse me from all unrighteousness.\n\nI have confessed. I now plead Your blood over my life, and I stand on Your Word: there is therefore now no condemnation to those who are in Christ Jesus. Who shall lay anything to the charge of God's elect? It is God who justifies. Who is he that condemns? It is Christ who died, and who is risen, and who intercedes for me.\n\nBe silent, accuser, in the name of Jesus. I will not carry what Christ has already carried. Give me a clear conscience and a thankful heart. If there is something real to put right with a person, show me, and I will do it. But I refuse shame that Your cross has already paid for. In Jesus' name, Amen.")],
 declare=["There is now no condemnation for me in Christ Jesus.","I am forgiven and cleansed by the blood of Jesus.","God remembers my sins no more.","I am the righteousness of God in Christ."])
