T = {}
T['marriage'] = dict(
 doc=["Marriage is the first institution God made, before government and before the church. In Genesis 2:24 the Lord names three movements: a man shall leave, he shall cleave, and they shall be one flesh. To leave means a new first loyalty. To cleave translates the Hebrew dabaq, which is the word for glue or something stuck fast. It describes a covenant bond, not a mood. Marriage is held together by promise, and feelings are meant to follow the promise, not the other way round.",
 "The doctrine of covenant is the heart of it. Malachi 2:14 calls the wife \"the wife of thy covenant,\" and Proverbs 2:17 speaks of \"the covenant of her God.\" A covenant is a vow made before God that binds you even when it costs you. This is why Scripture treats marriage as a picture of something larger: Paul says it is a great mystery concerning Christ and the church (Ephesians 5:32). A husband and wife are living out, in small, the way Christ keeps faith with His people.",
 "Genesis calls the woman an ezer kenegdo, a helper \"meet for him\" (Genesis 2:18). Ezer is a strong word. It is used of God Himself as the helper of Israel (Psalm 33:20). It never means a lesser person. Kenegdo means one who stands opposite and corresponds, an equal match who sees what the other cannot. Marriage is two whole people who complete what is missing in each other, in equal worth and in different strengths.",
 "Paul's instruction in Ephesians 5 begins with \"submitting yourselves one to another in the fear of God\" (verse 21), and the measure he sets for the husband is the cross: \"love your wives, even as Christ also loved the church, and gave himself for it.\" The pattern is sacrifice, not control. Peter adds that a husband who dishonours his wife finds his own prayers hindered (1 Peter 3:7). A marriage is a place where prayer and daily kindness are tied together."],
 christ="Revealed in Christ: Jesus is called the Bridegroom (Matthew 9:15; John 3:29). He pursued His bride at the cost of His life, and He keeps pursuing her. The vow He keeps with you is the standard and the supply for every vow you keep with your spouse. When you cannot find love in yourself, you can draw it from Him and give it on.",
 word="The word behind the word: in Genesis 2:24 the Hebrew for one is echad, the same word used in \"the Lord our God is one Lord\" (Deuteronomy 6:4). It is a unity that holds a plurality. Two remain two persons and become one household, one purpose, one covenant. Oneness is not sameness.",
 walk="Walk it out: Tonight, say one specific thing you are thankful for in your spouse and one thing you will do this week to serve them. Pray together, even if it is only one sentence. If you are single, pray for the marriages around you, and ask the Lord to make you a person of faithful words now.",
 key=['Genesis 2:18','Genesis 2:24','Ecclesiastes 4:9-12','Ephesians 5:25','Colossians 3:12-14','1 Corinthians 13:4-7'],
 prayers=[("Lord, keep our covenant","Father, You are the God who keeps covenant. You joined us together, and I bring my marriage to You as it is today, with its joys and its wounds. I thank You for the good You have placed in my spouse. Forgive me for every harsh word, every silence used as a weapon, every time I put myself first.\n\nLord, teach me to love as Christ loved: patiently, kindly, without keeping score. Where we have grown apart, bridge the distance. Where trust has been broken, begin to heal it, one honest conversation at a time. Guard our home from the lies of comparison and the pull of temptation. Let our words build and not tear down.\n\nMake us one in purpose and one in prayer. Let our home be a place where Your presence is welcome, and where the people who visit see something of Your faithfulness. Where I am single, Lord, prepare me and wait with me, and let me trust Your timing. In Jesus' name, Amen."),("Father, heal what hurts between us","Gracious Father, You see the tension in our home. I do not want to win an argument and lose a marriage. Give me the courage to listen first, the humility to say sorry first, and the patience to wait for answers.\n\nWhere pride has built a wall, bring it down. Where we have hurt each other in ways we cannot name, bring Your Spirit to the surface and heal it. Restore the friendship that started us. Renew the kindness and the laughter. Teach us to forgive as You forgave us, completely and without bringing it up again.\n\nLet nothing and no one come between us: not work, not money, not family pressure, not the phone. Keep our eyes on each other and on You, and let the love You poured into us keep running over into our home. In Jesus' name, Amen.")],
 declare=["My marriage is a covenant, and God keeps covenant with me.","Love is patient and kind in my home.","I choose forgiveness, honesty and faithfulness.","What God has joined, no one will separate."])

T['parenting'] = dict(
 doc=["Children are, in the words of Psalm 127:3, \"an heritage of the Lord.\" The Hebrew word for heritage speaks of something entrusted, not owned. You are a steward of lives that belong first to God. Parenting is therefore a calling before it is a task, and the first doctrine of parenting is humility: the children are His, and you are given a season to shape them toward Him.",
 "Proverbs 22:6 says, \"Train up a child in the way he should go.\" The Hebrew verb chanak, to train, carries the picture of a midwife rubbing the gums of a newborn with date juice to awaken the desire to suck. Training begins by awakening an appetite. The phrase \"in the way he should go\" is literally \"according to his way\" (al pi darko), which many scholars read as the child's own bent and personality. A wise parent studies the child God has made, and guides that child toward the Lord without crushing who they are.",
 "Deuteronomy 6:6-7 gives the method: God's words in your heart first, then \"thou shalt teach them diligently unto thy children, and shalt talk of them when thou sittest in thine house, and when thou walkest by the way, and when thou liest down, and when thou risest up.\" Faith is taught in the ordinary rhythms: meals, drives, bedtime. It is caught as much as taught. Children read the parent before they read the Bible.",
 "Paul gives the balance in Ephesians 6:4: fathers are not to provoke their children to wrath, but to bring them up \"in the nurture and admonition of the Lord.\" Nurture is the gentle side, admonition the corrective side. Hebrews 12 reminds us that God disciplines because He loves, and that is the model: correction that aims at the child's good, never at the parent's anger. Discipline without love breeds bitterness, and love without discipline breeds ruin."],
 christ="Revealed in Christ: Jesus said, \"Suffer the little children to come unto me, and forbid them not\" (Mark 10:14). He took them in His arms and blessed them. Your child is welcome to Him, and so are you, with every failure you carry. The Father you want to imitate is the Father who ran to the prodigal (Luke 15:20). You cannot be a perfect parent, but you can point to a perfect Father.",
 word="The word behind the word: \"nurture\" in Ephesians 6:4 is the Greek paideia, the whole training of a child including instruction and loving correction. \"Admonition\" is nouthesia, literally putting a thought into the mind. Both are acts of patient teaching, not of shouting.",
 walk="Walk it out: Choose one moment in the day, such as bedtime or the drive, to pray with your child by name. Tell them one thing you see God doing in them. If you have wronged your child, say sorry plainly. It teaches repentance better than a sermon.",
 key=['Psalms 127:3-5','Proverbs 22:6','Deuteronomy 6:6-7','Ephesians 6:4','Isaiah 54:13','3 John 1:4'],
 prayers=[("Father, my child belongs to You","Father, You gave me this child, and I give this child back to You. I thank You for the life You have entrusted to me. Forgive me where I have been impatient, distracted or harsh. Give me wisdom to know the child You made, and love that listens before it corrects.\n\nLord, protect my children from every harm of body and soul. Guard them from the lies of the world, from harmful friendships, from fear and shame. Draw them to know You early, and let them never have to unlearn Your goodness because of how I lived.\n\nHelp me to teach Your Word in the ordinary hours of our home. Let our house be a place of peace, honesty and laughter. When I do not know what to do, give me Your wisdom, which You give without reproach. When I fail, let Your grace cover my children where my strength falls short. In Jesus' name, Amen."),("Lord, bring my child home","Father, You know the child I am praying for. You know where they are tonight, in body and in heart. I cannot reach every place they go, but You are already there. I ask that Your Spirit would go after them as the shepherd went after the one sheep.\n\nSoften the hard places. Open their eyes to see Your love. Send people into their life who speak truth and kindness. Break the chains of addiction, anger, fear and wrong company, in the name of Jesus. Let them come to themselves, as the prodigal did, and let them find the way back.\n\nGive me the grace to wait without nagging, to love without condition, and to keep the door open. Heal my own heart of guilt and fear. I stand on Your promise that all my children shall be taught of the Lord, and great shall be their peace. In Jesus' name, Amen.")],
 declare=["My children are a heritage from the Lord.","God will teach my children, and great will be their peace.","My home serves the Lord.","I parent with patience, truth and grace."])

T['finance'] = dict(
 doc=["Scripture speaks about money more often than about many doctrines we call central, because money exposes whom we trust. The first truth is ownership: \"The earth is the Lord's, and the fulness thereof\" (Psalm 24:1). You are a steward, not an owner. A steward asks, \"What does the Master want done with what He has put in my hand?\" That one question changes budgeting, saving, spending and giving.",
 "The second truth is that God is a provider. Jehovah-Jireh, \"the Lord will see to it\" (Genesis 22:14), was named on the mountain where Abraham was about to give his most precious thing. Provision is not always early. It often arrives at the point of obedience. Philippians 4:19 says, \"my God shall supply all your need according to his riches in glory by Christ Jesus.\" The Greek verb supply, plerosei, means to fill to the full. Need is met from His riches, not from your account.",
 "Third, the Bible guards the heart. \"The love of money is the root of all evil\" (1 Timothy 6:10), not money itself. Jesus said you cannot serve God and mammon (Matthew 6:24). The danger is not owning, it is being owned. The cure is contentment, and the cure for greed is giving. Generosity breaks money's hold on the heart, which is why Scripture commands it before it is felt.",
 "Fourth, Proverbs is practical: diligence brings profit (Proverbs 10:4), the borrower is servant to the lender (22:7), plans made with counsel succeed (15:22), and a wise person saves while a fool consumes (21:20). Faith and planning are partners. God honours honest work and honest weights. Where debt, loss or lack is heavy, the answer is not shame but a step-by-step plan, wise counsel, and trust that He walks with you through it. This devotion is for encouragement and is not financial advice; speak to a qualified adviser about your situation."],
 christ="Revealed in Christ: \"Though he was rich, yet for your sakes he became poor, that ye through his poverty might be rich\" (2 Corinthians 8:9). The one who owned everything laid his riches down. He knows poverty from the inside, born in a borrowed stable and buried in a borrowed tomb. He is not a stranger to your lack, and He is the true treasure that cannot be taken.",
 word="The word behind the word: \"riches\" in Philippians 4:19 is ploutos, wealth in abundance. Paul does not say \"out of\" His riches in the way a rich man gives a coin from a large purse. He says \"according to\" them, meaning the supply is measured by the size of the store.",
 walk="Walk it out: Write down your income and your regular costs this week, honestly. Choose one thing to give, one thing to save and one thing to cut. Pray over the list. Ask a trusted person to hold you accountable.",
 key=['Psalms 24:1','Proverbs 3:9-10','Proverbs 21:5','Matthew 6:31-33','Philippians 4:19','Malachi 3:10','2 Corinthians 9:6-8'],
 prayers=[("Lord, You are my provider","Father, You are Jehovah-Jireh, the God who sees my need and provides. I bring my finances to You exactly as they are, with the bills, the debts and the fears. I confess that I have sometimes trusted my income more than You, and sometimes been careless with what You gave me.\n\nTeach me to steward well. Give me wisdom to plan, discipline to save, and a generous heart to give. Open honest doors of work and increase. Close the doors that would lead me into loss or dishonesty. Where I owe, show me the path to pay it off, and where I lack, supply from Your riches in glory.\n\nBreak the grip of greed and the fear of lack. Let me never love money more than You. I choose to seek first Your kingdom, trusting that what I need will be added. Thank You for every meal, every roof, every small mercy I have already received. In Jesus' name, Amen."),("Father, in a season of lack","Lord, tonight things are tight. I will not pretend otherwise before You. You said that You know what I have need of before I ask. I ask You for provision, for wisdom, for open doors, for work, for the right help at the right time.\n\nGuard my heart from shame and from comparison. Protect my family from desperate decisions. Keep me honest when dishonesty looks easier. Give me favour with the people who can help, and give me the humility to ask when I need to.\n\nI remember Your faithfulness: the oil that did not run dry, the bread that fed a crowd, the ravens that fed Elijah. You have not forgotten me. I believe that You will make a way. Let my lack become a place where I meet You more deeply. In Jesus' name, Amen.")],
 declare=["The earth is the Lord's, and I am His faithful steward.","My God supplies all my needs according to His riches in glory.","I am free from the love of money.","I give with joy and I work with diligence."])

T['purpose'] = dict(
 doc=["Purpose is not something you invent. It is something you discover in the One who made you. Ephesians 1:11 says we were \"predestinated according to the purpose of him who worketh all things after the counsel of his own will.\" Before you had any plan, God had one. Your first purpose, the one that underlies every other, is to know Him and glorify Him (Isaiah 43:7; John 17:3).",
 "Jeremiah 29:11 is often quoted: \"I know the thoughts that I think toward you, saith the Lord, thoughts of peace, and not of evil, to give you an expected end.\" The Hebrew for thoughts is machashavot, plans and designs. The Hebrew for expected end is acharit v'tikvah, a future and a hope. Notice the context: these words were written to exiles in Babylon, people whose circumstances looked like the opposite of purpose. God's plan does not wait for ideal conditions.",
 "Ephesians 2:10 tells us, \"we are his workmanship, created in Christ Jesus unto good works, which God hath before ordained that we should walk in them.\" The Greek for workmanship is poiema, from which we get the word poem. You are God's composition, His work of art. And the good works were prepared in advance. Your task is not to build a destiny from nothing but to walk into what He has prepared, one faithful step at a time.",
 "Purpose is lived out in small obedience. Joseph's dreams were followed by years of slavery and prison before they were fulfilled. David was anointed king and then returned to the sheep. God uses unseen faithfulness to prepare for open calling. \"He that is faithful in that which is least is faithful also in much\" (Luke 16:10). Do the next right thing, where you are, with all your heart, as unto the Lord (Colossians 3:23). Purpose is found there."],
 christ="Revealed in Christ: Jesus said, \"I have glorified thee on the earth: I have finished the work which thou gavest me to do\" (John 17:4). He lived with a clear purpose, and He completed it, so that yours would never be lost. In Him your life is not an accident. And your calling is joined to His: to make the Father known.",
 word="The word behind the word: \"workmanship\" in Ephesians 2:10 is poiema, the same root as poem. Your life is being written by a Master Author. A single line may not make sense by itself, but the whole is meant to be beautiful.",
 walk="Walk it out: Write three answers: What has God put in my hand? Who has He put in my path? What is the next faithful step? Do that step today, however small. Ask one trusted believer what they see God doing in you.",
 key=['Jeremiah 29:11','Ephesians 2:10','Romans 8:28','Proverbs 19:21','Psalms 138:8','Colossians 3:23','Luke 16:10'],
 prayers=[("Lord, show me my purpose","Father, You made me on purpose and for a purpose. I surrender my own plans to You and ask You to show me Yours. Let me not live by drift, by comparison or by fear. Settle my heart on the one thing that matters: to know You and make You known.\n\nOpen the doors You want open, and close the ones that lead away from You. Show me the good works You prepared for me before I was born. Give me the faithfulness to be obedient in small things, to work with all my heart, and to wait for Your timing without losing hope.\n\nWhere I feel I have wasted years, redeem the time. Where I feel I am too small, remind me that You choose the weak. Give me ears to hear, courage to step and humility to serve. Let my life be a poem that brings You glory. In Jesus' name, Amen."),("Father, while I wait","Lord, I am in a season of waiting, and it feels long. I trust that You are not wasting it. Like Joseph in prison, like Moses in the desert, like David with the sheep, let this season shape me for what You have prepared.\n\nGuard me from bitterness and from envy of those who seem ahead of me. Teach me to be faithful where I am, to do small things with great love. Give me patience in the waiting, and let my character grow deeper than my gifts.\n\nI thank You that You work all things together for good. I choose to believe that what You started in me, You will finish. Direct my steps, establish the work of my hands, and let me recognise Your hand when it comes. In Jesus' name, Amen.")],
 declare=["I am God's workmanship, created for good works.","God's plans for me are for peace and a future and a hope.","The Lord will perfect that which concerns me.","I am faithful in little and ready for more."])

T['health'] = dict(
 doc=["The Bible takes the body seriously. God made it and called it very good (Genesis 1:31), the Son of God took one (John 1:14), and the Holy Spirit makes it His temple (1 Corinthians 6:19). So illness is neither unimportant nor a sign of a hidden sin by default. Job's friends were wrong to say it was. Jesus said of the man born blind that it was not sin, but that the works of God should be displayed (John 9:3).",
 "God's name as healer comes from Exodus 15:26: \"I am the Lord that healeth thee,\" Jehovah-Rapha. The Hebrew rapha means to mend, to restore, to stitch together. It is used of bodies, of broken hearts (Psalm 147:3), of land and of nations. God heals in many ways: directly, through doctors and medicine, through rest and care, through the community of believers, and in the final resurrection when every tear is wiped away. Using medicine is not a lack of faith; Luke was a physician and Paul told Timothy to take a little wine for his stomach (1 Timothy 5:23).",
 "James 5:14-15 invites the sick to call for the elders of the church, who pray and anoint with oil, \"and the prayer of faith shall save the sick.\" The Greek sozo means to save, to heal and to make whole. God's concern is the whole person, body, mind, spirit and relationships. Sometimes He heals quickly, sometimes slowly, and sometimes He gives grace to endure. Paul prayed three times that his thorn would be removed, and the answer was, \"My grace is sufficient for thee\" (2 Corinthians 12:9). That is not a failure of prayer. It is a different answer from a Father who sees everything.",
 "Faith does not mean denying symptoms or refusing care. It means bringing them to God while doing what is wise. Take your medicine, see your doctor, rest, eat well, and pray. For long illness, God also heals the heart: He is near to the brokenhearted. If you are caring for someone who is sick, your service is seen by Him. This devotion does not replace medical advice; please see a doctor or nurse for any health concern."],
 christ="Revealed in Christ: Matthew applies Isaiah to Jesus: \"Himself took our infirmities, and bare our sicknesses\" (Matthew 8:17). He healed because He had compassion, and He still has it. He also carries the scars of His own suffering, so He understands pain. Every healing He did was a sign of the world that is coming, where there is no more death, nor sorrow, nor crying, neither shall there be any more pain (Revelation 21:4).",
 word="The word behind the word: \"Rapha\" in Exodus 15:26 is related to the word for a physician. God puts Himself in the position of the doctor of His people. The name Jehovah-Rapha was given at Marah, at the bitter water made sweet, which shows that healing begins where we meet bitterness with trust.",
 walk="Walk it out: Name the health concern before God plainly. Book the appointment or take the step you have been avoiding. Ask one person to pray with you. Thank Him for one part of your body that is working today.",
 key=['Exodus 15:26','Psalms 103:2-3','Psalms 147:3','Isaiah 53:5','James 5:14-15','Jeremiah 30:17','2 Corinthians 12:9'],
 prayers=[("Lord, You are my healer","Father, You are Jehovah-Rapha, the Lord who heals. I bring my body to You, with every pain, every test result and every fear. I thank You that you made me wonderfully. I ask for healing in Jesus' name.\n\nGive wisdom to my doctors and nurses. Guide every treatment and every decision. Where there is infection, inflammation or disease, speak peace. Strengthen what is weak. Give me patience in the waiting rooms and courage in the hard conversations. Keep me from despair, and fill my room with Your peace.\n\nI believe that You are able, and I trust You whether the answer is quick or slow. Let nothing steal my hope, and let this season draw me closer to You. Hold my family and caregivers up. I give You thanks in advance, and I give You all the glory. In Jesus' name, Amen."),("Father, strengthen the one who is sick","Lord, I stand in the gap for someone I love who is sick. You see them. You know the name, the diagnosis and the fear. I ask for Your healing touch, in whatever way You choose.\n\nBe their comfort in the night. Be their strength in the treatment. Surround them with people who love them well. Where they are afraid, give them peace beyond understanding. Where they are tired, renew their strength like the eagles.\n\nGive me wisdom to serve them, patience when I am weary, and words that bring life. Let this trial deepen our faith and not shrink it. Whatever the outcome, let us know that You are near. In Jesus' name, Amen.")],
 declare=["The Lord is my healer.","My body is a temple of the Holy Spirit.","God's grace is sufficient for me.","I trust Him with my health and my future."])

T['doubt'] = dict(
 doc=["Doubt is not the opposite of faith. Unbelief is. Doubt is faith asking a question. The Bible is full of honest doubters: Abraham, Gideon, Thomas, John the Baptist in prison, and a father who said to Jesus, \"Lord, I believe; help thou mine unbelief\" (Mark 9:24). Jesus did not turn any of them away. He answered each one with patience and evidence.",
 "The Greek word for doubt in the New Testament is often distazo, to stand in two places, or dipsychos, double-minded, \"two-souled\" (James 1:8). Doubt is not a lack of intelligence. It is a divided loyalty, one foot on the rock and one on the waves. When Peter walked on the water he did well until he saw the wind and began to sink. Jesus did not say, \"You have no faith.\" He said, \"O thou of little faith, wherefore didst thou doubt?\" (Matthew 14:31). Little faith is still faith, and He caught Peter's hand.",
 "Faith has foundations. John wrote his Gospel \"that ye might believe\" (John 20:31). Luke wrote \"that thou mightest know the certainty\" (Luke 1:4). The resurrection was witnessed by hundreds (1 Corinthians 15:3-8). Creation, conscience and the coherence of Scripture all testify. Honest questions are welcome, and answers exist. The way through doubt is to bring it to God, to the Word and to wise believers, not to hide it.",
 "Some things we will not understand now. \"For now we see through a glass, darkly; but then face to face\" (1 Corinthians 13:12). Faith is not certainty about every detail; it is trust in a person. Thomas wanted to touch the wounds, and Jesus invited him, then said, \"blessed are they that have not seen, and yet have believed\" (John 20:29). Walk with God long enough, and the memories of His faithfulness will outweigh the questions."],
 christ="Revealed in Christ: Jesus meets doubt with nearness. He walked with the two on the road to Emmaus and explained the Scriptures (Luke 24:27). He showed Thomas His hands. He is not threatened by your questions. He is the answer, the one in whom all the treasures of wisdom and knowledge are hidden (Colossians 2:3).",
 word="The word behind the word: in James 1:6 the doubter is \"like a wave of the sea driven with the wind and tossed.\" The Greek picture is a sea that has no anchor. Hebrews 6:19 offers the opposite: hope as \"an anchor of the soul, both sure and stedfast.\" Anchor your questions to Christ.",
 walk="Walk it out: Write down the honest question. Next to it, write what you do know for sure about God's character. Read John 20 slowly. Then talk to a wise believer, a pastor or a friend. Questions shared lose their power to isolate.",
 key=['Mark 9:23-24','Matthew 14:29-31','John 20:27-29','James 1:5-6','Hebrews 11:1','Hebrews 6:19','Jude 1:22'],
 prayers=[("Lord, help my unbelief","Father, I come to You as I am, with faith and with questions. I believe, Lord; help my unbelief. I do not want to pretend, and I do not want to drift. Meet me in the place where my faith feels thin.\n\nGive me honest answers, and give me peace where answers do not come. Remind me of the times You have been faithful. Show me again who Jesus is. Guard my mind from the lies that say You are distant or uncaring. Lead me to people who can walk with me, and to Your Word, which is truth.\n\nLike Thomas, I need to know that You are real. Reveal Yourself to me. Anchor my soul, so that the waves do not sink me. Grow my faith until it holds even when I cannot see. In Jesus' name, Amen."),("Father, steady me","Lord, my mind is restless tonight. Voices say that You are not there, that prayer is empty, that I have been fooled. I bring these voices to You instead of to my own fears.\n\nSpeak louder than the doubt. Let Your Spirit bear witness with my spirit that I am Your child. Bring back to mind the moments You have answered, comforted and carried me. Keep me from being tossed like a wave. Make me single-minded in my love for You.\n\nGive me hunger for Your Word, and humility to ask for help. I thank You that You do not break a bruised reed. I take Your hand as Peter did, and I trust You to hold me. In Jesus' name, Amen.")],
 declare=["Lord, I believe; help my unbelief.","Hope is the anchor of my soul.","Faith comes by hearing the Word of God.","He who began a good work in me will complete it."])

T['temptation'] = dict(
 doc=["Temptation is not sin. Jesus was \"in all points tempted like as we are, yet without sin\" (Hebrews 4:15). The moment of testing is not the moment of failure. Sin begins when desire is welcomed and acted on (James 1:14-15). That is the anatomy of a fall: desire, then enticement, then conception, then sin, then death. If you can interrupt it early, you win.",
 "The Greek word peirasmos can mean a test or a temptation, depending on its purpose. God never tempts anyone to sin (James 1:13), but He allows tests that prove and strengthen faith. The same circumstance can be a test from God, to bring out your faith, and a temptation from the enemy, to bring out your failure. The difference is the direction in which you are pulled: toward obedience or away from it.",
 "1 Corinthians 10:13 is a great promise: \"There hath no temptation taken you but such as is common to man: but God is faithful, who will not suffer you to be tempted above that ye are able; but will with the temptation also make a way to escape.\" The Greek for a way to escape is ekbasis, an exit, a way out of a narrow place, like a pass through mountains. Every temptation has a door. Your task is to walk through it, often by literally leaving the room, closing the screen or calling a friend.",
 "Jesus' own method in the wilderness was the Word: \"It is written.\" Three times He answered the devil from Deuteronomy (Matthew 4). Psalm 119:11 says, \"Thy word have I hid in mine heart, that I might not sin against thee.\" Prepare before the battle: memorise Scripture, avoid places of weakness, keep accountable friends, and flee. The Bible does not tell us to stand and debate with some temptations. It tells us to flee (1 Corinthians 6:18; 2 Timothy 2:22). And if you fall, 1 John 1:9 stands open: confess, and He is faithful and just to forgive."],
 christ="Revealed in Christ: He was tempted in every way and did not sin, and because He did, He is able to succour those who are tempted (Hebrews 2:18). He has been where you are, and He has won where you lose. His victory is credited to you, and His Spirit is given to you for the fight.",
 word="The word behind the word: \"succour\" in Hebrews 2:18 is the Greek boetheo, to run to a cry for help. When you cry, Jesus runs toward you. You do not need to be strong first. You need to call.",
 walk="Walk it out: Name your weak spots: the time, the place, the device, the company. Remove one trigger today. Memorise one verse for the moment of temptation. Tell one trusted person where you struggle, and ask them to check on you.",
 key=['1 Corinthians 10:13','James 1:12-15','Hebrews 4:15-16','Matthew 26:41','Psalms 119:9-11','Ephesians 6:11'],
 prayers=[("Lord, lead me away from temptation","Father, You taught us to pray, \"lead us not into temptation, but deliver us from evil.\" I pray it now. You know where I am weak. You know the thoughts that keep returning. I bring them into the light, because darkness is where they grow.\n\nGive me the grace to flee. Open the way of escape that You promised, and give me the courage to take it. Put Your Word into my mouth when I am pressed. Surround me with believers who will ask me hard questions. Strengthen my will, and renew my desires so that I long for what is holy more than what is harmful.\n\nI put on the armour of God: truth, righteousness, peace, faith, salvation and the Word. Jesus, You overcame, and I stand in Your victory. Where I have fallen, forgive me and wash me clean. Let my failures drive me to You and not away from You. In Jesus' name, Amen."),("Father, in the moment of weakness","Lord, I am close to a line tonight. I can feel the pull. I call on You right now, as the one who runs to a cry for help. Come quickly. Make me strong where I am weak.\n\nI renounce this temptation in the name of Jesus. I will not give it a place. I choose to leave, to look away, to call a friend, to open Your Word. Fill my mind with what is pure, lovely and of good report. Give me the joy of obedience that is greater than the pleasure of sin.\n\nThank You that Your mercy is new every morning, and that a fall does not end the story. Make me faithful. Keep me watching and praying. In Jesus' name, Amen.")],
 declare=["God is faithful and provides a way out.","Greater is He that is in me than he that is in the world.","I resist the devil, and he flees from me.","I am more than a conqueror through Christ."])

T['peace'] = dict(
 doc=["Peace in the Bible is much more than quiet. The Hebrew shalom means wholeness, completeness, welfare: everything being as God intends. It is used for greeting and blessing because it wishes a person the fullness of well-being. When Jesus says, \"Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you\" (John 14:27), He gives His own settled wholeness, not an absence of problems.",
 "Isaiah 26:3 says, \"Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee.\" In Hebrew the phrase is shalom shalom, peace, peace, a doubling that means peace upon peace. The word for stayed, samakh, means to lean, to rest your full weight on something. Peace comes when your mind leans its whole weight on God, rather than on circumstances.",
 "Romans 5:1 gives the foundation: \"Therefore being justified by faith, we have peace with God through our Lord Jesus Christ.\" Before there can be the peace of God, there must be peace with God. The enmity was ended at the cross. Colossians 1:20 says He \"made peace through the blood of his cross.\" Everything else flows from this. A person who has been reconciled to God has a ground of peace that no shifting circumstance can remove.",
 "Philippians 4:7 says that \"the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.\" It passes understanding: it does not make sense by the world's logic. Peace in a hospital room, peace in loss, peace in uncertainty. It is a fruit of the Spirit (Galatians 5:22), grown, not forced. And Colossians 3:15 says to let it \"rule\" in your hearts. The word rule is brabeuo, to act as umpire. When voices clash inside you, let peace make the call."],
 christ="Revealed in Christ: He is called the Prince of Peace (Isaiah 9:6). He slept in the storm, and He stilled it with three words: \"Peace, be still\" (Mark 4:39). The same voice speaks to your inner storm. After the resurrection, His first word to the frightened disciples was, \"Peace be unto you\" (John 20:19). Peace is a Person who walks into the room.",
 word="The word behind the word: \"shalom\" comes from a root meaning to be whole or to pay in full. In Christ the debt is paid in full, and so your peace is the peace of a settled account.",
 walk="Walk it out: Sit still for two minutes. Breathe slowly. Pray Isaiah 26:3 back to God, replacing \"him\" with \"me.\" Hand over the one thing that is stealing your peace. Then do one small, kind thing for someone else.",
 key=['John 14:27','Isaiah 26:3','Philippians 4:6-7','Colossians 3:15','Romans 5:1','Numbers 6:24-26','Psalms 4:8'],
 prayers=[("Prince of Peace, rule my heart","Lord Jesus, Prince of Peace, I come to You tired of the noise inside me. You said that Your peace is not like the world's peace. I ask for it now. Let it settle on my thoughts, my body, my home.\n\nI confess that I have leaned my weight on circumstances, on people and on my own plans, and they have shaken. Today I lean my whole weight on You. Keep my mind stayed on You, and keep me in perfect peace.\n\nWhere there is conflict, make me a peacemaker. Where there is fear, speak, \"Peace, be still.\" Let Your peace guard my heart and mind, and let it overflow to those around me. Thank You that I am at peace with God through You. In Jesus' name, Amen."),("Father, give me rest tonight","Father, the day is ending and my mind is still running. I place the day in Your hands: what I did, what I did not do, the words I said, the worries I carry. I will not sleep on them. I give them to You.\n\nThank You for being awake when I am asleep. Thank You for being in control when I am not. Let Your peace wrap around me like a blanket. Quiet the voices of worry and regret. Let me lie down in peace, for You alone make me dwell in safety.\n\nWatch over my family, my home and the people I love. And let tomorrow find me rested and ready to walk with You. In Jesus' name, Amen.")],
 declare=["The peace of God guards my heart and mind.","I am at peace with God through Jesus Christ.","My mind is stayed on Him.","I lie down and sleep in peace."])
