T = {}
T['hope'] = dict(
 doc=["Biblical hope is not wishful thinking. The Hebrew word tikvah comes from a root meaning a cord or line. In Joshua 2, Rahab tied a scarlet cord (tikvah) in her window, and that cord was her rescue. Hope is a cord that is tied to something real. Hebrews 6:19 calls it \"an anchor of the soul, both sure and stedfast, and which entereth into that within the veil.\" Your anchor is fixed not in the shifting sea but in the presence of God.",
 "A second Hebrew word, qavah, means to wait, to twist together like strands of a rope. Isaiah 40:31 says, \"they that wait upon the Lord shall renew their strength.\" To wait on the Lord is to be braided into His strength until two strands become one. Hope is active, not idle. It stretches toward a promise, and the stretching makes the rope strong.",
 "Romans 5:3-5 gives the chain: tribulation works patience, patience works experience, experience works hope, \"and hope maketh not ashamed; because the love of God is shed abroad in our hearts by the Holy Ghost.\" Suffering does not destroy hope when God's love is already poured into us. The proof is the cross: \"He that spared not his own Son... how shall he not with him also freely give us all things?\" (Romans 8:32).",
 "Christian hope looks forward to a defined end: the return of Christ, the resurrection of the body, and a new heaven and new earth where God dwells with His people (1 Thessalonians 4:13-18; Revelation 21:1-5). This means no grave is the last word, no diagnosis, no failure, no loss. Paul says we sorrow, but not as others who have no hope. Hope does not remove tears; it surrounds them with a promise."],
 christ="Revealed in Christ: He is called \"Christ in you, the hope of glory\" (Colossians 1:27). Hope is a Person. The empty tomb is the guarantee that every promise will be kept, because the One who made them rose from the dead and is alive (1 Peter 1:3).",
 word="The word behind the word: tikvah is the cord in Rahab's window. Look for the scarlet thread in your own story, the line of God's faithfulness that runs through the hardest times. Tie your hope to it.",
 walk="Walk it out: Write down three times God has come through for you. Underline one promise from Scripture that fits your situation today. Say it aloud three times. Then tell someone who is discouraged about it.",
 key=['Romans 15:13','Hebrews 6:18-19','Lamentations 3:21-23','Isaiah 40:31','Jeremiah 29:11','Romans 5:3-5','1 Peter 1:3'],
 prayers=[("God of hope, fill me","Father, You are the God of hope. I confess that I have let circumstances tell me that hope is gone. I bring You my disappointment, my waiting and my unanswered prayers. Fill me with all joy and peace in believing, that I may abound in hope by the power of the Holy Spirit.\n\nTie my heart to Your promises like a cord to an anchor. Let me not be driven by every wave. Remind me that Jesus is alive, that the grave has lost, and that You are working even where I cannot see.\n\nRenew my strength as I wait on You. Give me eyes for the new things You are springing up. Let me be a person who carries hope to others, speaking life in dark places. Thank You that Your mercies are new every morning and great is Your faithfulness. In Jesus' name, Amen."),("Lord, when hope is thin","Lord, tonight hope is thin. I do not have the words, but You know my heart. I ask You to be the strength of my heart and my portion forever.\n\nPlease send someone to encourage me, or let a verse find me. Let me remember something good You have done. Lift my head. Remind me that weeping may endure for a night, but joy comes in the morning.\n\nI choose to wait on You. I choose to believe that You are good, that You are near, and that You are at work. Do not let me be put to shame. Let my hope rest on You alone. In Jesus' name, Amen.")],
 declare=["Christ in me is my hope of glory.","My hope is an anchor for my soul.","I wait on the Lord and my strength is renewed.","God's mercies are new every morning."])

T['strength'] = dict(
 doc=["The Bible's strength is not self-made. Psalm 46:1 says, \"God is our refuge and strength, a very present help in trouble.\" Strength here is a gift, found in a Person. Paul learned the lesson in a hard way when he asked three times to be rid of his thorn and heard, \"My strength is made perfect in weakness\" (2 Corinthians 12:9). His conclusion is startling: \"when I am weak, then am I strong.\" It is when we stop pretending to be strong that His strength becomes visible.",
 "Isaiah 40:31 promises, \"they that wait upon the Lord shall renew their strength.\" The Hebrew verb for renew, chalaph, means to exchange, as one changes clothes. We swap our strength for His. You give Him tiredness, and He gives you stamina. The context is important: Isaiah says even the youths faint and fall (verse 30). No human strength is enough. Only those who wait on God mount up with wings.",
 "Philippians 4:13 is often quoted: \"I can do all things through Christ which strengtheneth me.\" Its context is contentment in both plenty and hunger. The strength Paul speaks of is not the power to win every ambition but the power to endure and to be content in any condition. The Greek endunamoo means to pour power into someone. It is a continuous empowering, not a one-off.",
 "Ephesians 6:10 commands, \"be strong in the Lord, and in the power of his might.\" The strength is located in Him. Then come the armour pieces: truth, righteousness, the gospel of peace, faith, salvation and the Word. Strength is also found in the community, for \"a threefold cord is not quickly broken\" (Ecclesiastes 4:12). Rest is part of strength: Jesus withdrew to quiet places, and even the strongest need Sabbath. Do not be ashamed to ask for help."],
 christ="Revealed in Christ: He is \"the power of God, and the wisdom of God\" (1 Corinthians 1:24). The strongest moment in history looks like weakness: a man on a cross. In that weakness He broke death. The power that raised Him from the dead lives in those who believe (Ephesians 1:19-20).",
 word="The word behind the word: \"renew\" in Isaiah 40:31 is chalaph, to exchange or to pass on through. It is the word for sprouting a fresh shoot from a stump, and for putting on new clothes. Your strength is not repaired; it is replaced.",
 walk="Walk it out: Tell the Lord the area where you feel weakest. Say aloud, \"I give You my weakness, give me Your strength.\" Then do the next small task. Get rest and a proper meal, and ask a friend for help with something heavy.",
 key=['Isaiah 40:29-31','Psalms 46:1','Philippians 4:13','2 Corinthians 12:9-10','Ephesians 6:10','Nehemiah 8:10','Psalms 28:7'],
 prayers=[("Lord, be my strength","Father, I am tired, and I do not have enough in myself. I give You my weakness. Exchange my strength for Yours, as You promised. Let me mount up with wings as eagles, run and not be weary, walk and not faint.\n\nI thank You that Your strength is made perfect in weakness. Teach me to boast not in what I can do but in what You do through me. Where I am carrying more than I should, show me what to put down. Where I need help, give me the humility to ask.\n\nFill me with the joy of the Lord, which is my strength. Pour power into me as You did into Paul. Help me to stand in the evil day, clothed in Your armour. Be my rock, my fortress and my high tower. In Jesus' name, Amen."),("Father, I am worn out","Lord, I am worn thin. Some days I do not know how to keep going. I bring You my exhaustion, my responsibilities and the people who lean on me.\n\nGive me rest that goes deeper than sleep. Give me the strength for today only, since You promised strength equal to my days. Show me what is mine to do and what is Yours. Send me help in the form of kindness, wisdom and community.\n\nI wait on You. I lift my eyes to the hills, knowing that my help comes from You. Hold me up with Your righteous right hand. Let me rise again, not in my own power, but in Yours. In Jesus' name, Amen.")],
 declare=["The Lord is my strength and my shield.","I can do all things through Christ who strengthens me.","When I am weak, He is strong.","I wait on the Lord and I do not faint."])

T['identity'] = dict(
 doc=["Who you are is settled by what God says, not by what others have said or by what you have done. Genesis 1:27 says we are made \"in the image of God.\" Every person bears His likeness, which gives worth that no failure can erase. Psalm 139:14 adds, \"I am fearfully and wonderfully made.\" You were not a mistake. Your life was intended.",
 "In Christ the identity is made new. 2 Corinthians 5:17 says, \"if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new.\" The Greek is kaine ktisis, a new creation, new in kind and not merely renovated. John 1:12 says, \"as many as received him, to them gave he power to become the sons of God.\" You are not a servant on probation; you are a child.",
 "Paul uses the word huiothesia, adoption as sons, in Romans 8:15 and Galatians 4:5-7. In Roman law an adopted son was fully an heir, with all debts cleared and a new name. It was a legal act with lasting effect. Because of it, \"ye have received the Spirit of adoption, whereby we cry, Abba, Father.\" Abba is the intimate address of a child to a father. Orphans of this world become sons and daughters of the King.",
 "Ephesians 1 and 2 list what is true of you: chosen, adopted, accepted, redeemed, forgiven, sealed, seated with Christ, and made alive. 1 Peter 2:9 calls believers \"a chosen generation, a royal priesthood, an holy nation, a peculiar people.\" You can lay down labels: failure, rejected, too much, not enough. The enemy accuses; Christ declares. Let His voice be the loudest. Identity is received, not earned. It is rooted in His love, and it produces confidence, humility and service."],
 christ="Revealed in Christ: at His baptism, before He did a single miracle, the Father said, \"This is my beloved Son, in whom I am well pleased\" (Matthew 3:17). Sonship came before service. In Christ, the same love is spoken over you, before and apart from your performance.",
 word="The word behind the word: \"workmanship\" in Ephesians 2:10 is poiema, a work of art, and \"new creature\" is kaine ktisis, a new creation. You are not patched; you are made new, and made on purpose.",
 walk="Walk it out: Write down one label you carry that God did not give you. Next to it, write a verse that tells the truth. Read the verse aloud each morning this week. When the old label returns, answer it with the verse.",
 key=['Genesis 1:27','Psalms 139:13-16','2 Corinthians 5:17','John 1:12','Romans 8:15-17','1 Peter 2:9','Ephesians 1:4-6'],
 prayers=[("Father, tell me who I am","Father, I thank You that You made me in Your image and that You know me by name. I come to You tired of the voices that tell me who I am: the voice of the past, the voice of other people, the voice of my own failures. I lay them down.\n\nSpeak over me what You say. Let me hear that I am Your child, chosen, loved and accepted in Christ. Help me to believe it, not only in my head but in my bones. Let the Spirit of adoption cry \"Abba, Father\" in me.\n\nHeal the places in me that were told I was not enough. Free me from the need to perform for love. Let me walk with a quiet confidence that does not need to prove itself or put others down. Make me a new creation, living from Your love. In Jesus' name, Amen."),("Lord, deliver me from comparison","Lord, I compare myself to others, and I always lose. Forgive me for envy and for despising what You made in me. You made me on purpose, and You gave me gifts and a story that are mine.\n\nTeach me to celebrate others without shrinking myself. Silence the accuser, who reminds me of what I have done. Speak the finished work of Jesus over me, that there is no condemnation for those who are in Christ.\n\nSettle me in my place in Your family. Let me live from acceptance, not for acceptance. And let others who look at my life see how good it is to be Your child. In Jesus' name, Amen.")],
 declare=["I am a child of God.","I am a new creation in Christ.","I am fearfully and wonderfully made.","I am chosen, loved and accepted."])

T['gratitude'] = dict(
 doc=["Gratitude is commanded in Scripture because it is good for us: \"In every thing give thanks: for this is the will of God in Christ Jesus concerning you\" (1 Thessalonians 5:18). It says in everything, not for everything. We do not thank God for evil, but we thank Him in it, because He is present in it and working in it. Thanks is an act of faith that declares that God is still good.",
 "The Greek word for giving thanks is eucharisteo, from eu (good) and charis (grace). Thanks is a response to grace. It is also the root of our word Eucharist, because Jesus \"gave thanks\" before breaking the bread (Luke 22:19), and He did so on the night before His death. If He could give thanks on that night, we can learn to give thanks in ours.",
 "The Hebrew word todah, thanksgiving, comes from a root meaning to extend the hand. It is the open hand of thanks. It was the name of a sacrifice (Psalm 50:14, 23; Psalm 107:22). Thanks is an offering. Psalm 100 gives the way in: \"Enter into his gates with thanksgiving, and into his courts with praise.\" Thanks opens the door to His presence.",
 "Ingratitude, in contrast, begins the spiral in Romans 1:21: \"when they knew God, they glorified him not as God, neither were thankful.\" Grumbling shrinks the heart. The Israelites in the wilderness complained about the very mercies that rescued them. Gratitude trains the eyes to see the gift. It also protects against comparison, entitlement and anxiety, because a thankful heart is a full one. Count what you have, and remember what He has done."],
 christ="Revealed in Christ: He thanked the Father before the miracle (John 11:41), before the meal (Matthew 15:36) and before the cross (Luke 22:19). Thanks was His posture of trust. He is also the greatest gift, \"Thanks be unto God for his unspeakable gift\" (2 Corinthians 9:15). All other gratitude flows from this.",
 word="The word behind the word: eucharisteo holds charis, grace, inside it. Thanks is grace recognised. The more you notice grace, the more you thank, and the more you thank, the more you notice.",
 walk="Walk it out: Write three things you are thankful for each day this week, and make each different. Thank one person by name, in writing or in person. Thank God for something that you once prayed for and now have.",
 key=['1 Thessalonians 5:16-18','Psalms 100:1-5','Psalms 103:1-5','Colossians 3:15-17','Philippians 4:6','Psalms 107:1','Lamentations 3:22-23'],
 prayers=[("Father, I give You thanks","Father, I thank You. Before I ask for anything, I thank You for life, for breath, for this day. Thank You for the roof over me, the food on my table, the people who love me, the Bible in my hand. Thank You for the things I take for granted.\n\nForgive me for the times I have complained about the very mercies that You gave. Open my eyes to see small gifts: a kind word, a clear morning, a safe journey, a healed relationship. Thank You most of all for Jesus, Your unspeakable gift, who bore my sin and gave me life.\n\nLet my life be a thank offering. Let my mouth speak praise and my hands give freely. Teach me to give thanks in everything, knowing that You are good and Your mercy endures forever. In Jesus' name, Amen."),("Lord, teach me to thank You in the hard times","Lord, it is hard to be thankful tonight. Some things in my life are not as I wanted. I will not pretend. But I choose to bring You a sacrifice of thanksgiving, even if it costs me.\n\nI thank You that You are with me. I thank You that this will not last forever. I thank You that You have carried me before, and that Your mercies are new each morning. I thank You for the people who stood by me, and for the lessons that came only through pain.\n\nLet thankfulness lift my eyes from what is missing to what You have given. Turn my complaining into praise. And let gratitude grow into joy that no circumstance can take away. In Jesus' name, Amen.")],
 declare=["I give thanks in every circumstance.","The Lord's mercies are new every morning.","I enter His gates with thanksgiving.","My heart is full of gratitude to God."])

T['prayer'] = dict(
 doc=["Prayer is conversation with the God who hears. It is not a technique to manipulate Him. It is a relationship with a Father. Jesus' first instruction in Matthew 6:6 is to go into a private place, shut the door, and pray \"to thy Father which is in secret.\" The word is Father. Prayer starts with the fact that He is near and that He wants to hear from you.",
 "The Hebrew verb palal, to pray, is reflexive. It means to judge oneself, or to intercede. In prayer we are examined and aligned as well as heard. The Greek proseuchomai joins pros (toward) with euchomai (to wish or vow). Prayer is a turning toward God. And Jesus taught that persistence matters. In Luke 11:9 the verbs are in the present tense: \"Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened.\" Keep asking, keep seeking, keep knocking.",
 "The model prayer in Matthew 6:9-13 gives a shape: honour the Father's name, pray for His kingdom and will, ask for daily bread, ask for forgiveness and give it, ask for protection. Notice that it begins with God, and moves to our needs. The Spirit helps us when we do not know what to pray: \"the Spirit itself maketh intercession for us with groanings which cannot be uttered\" (Romans 8:26). Even your sighs count.",
 "Prayer is not always answered the way we ask. Answers can be yes, no, wait or something better. Jesus Himself prayed, \"if it be possible, let this cup pass from me: nevertheless not as I will, but as thou wilt\" (Matthew 26:39). Sin can hinder prayer (Psalm 66:18), as can unforgiveness (Mark 11:25) and wrong motives (James 4:3). But the open door remains: \"Let us therefore come boldly unto the throne of grace\" (Hebrews 4:16). Pray in faith, in Jesus' name, in the Spirit, and in line with His Word."],
 christ="Revealed in Christ: \"he ever liveth to make intercession for them\" (Hebrews 7:25). While you pray, Jesus prays for you. Your prayers rise through the High Priest. He also prayed early in the morning (Mark 1:35) and all night (Luke 6:12), teaching us to prize time with the Father.",
 word="The word behind the word: In Luke 11:9 \"ask, seek, knock\" are present imperatives, which means keep on asking, keep on seeking, keep on knocking. Prayer is persistence in relationship, not a single request.",
 walk="Walk it out: Choose a regular time and place. Use the Lord's Prayer as a pattern, one line at a time. Pray for three people by name. Keep a short prayer list, and write down answers when they come.",
 key=['Matthew 6:6-13','Philippians 4:6-7','Luke 11:9-10','Romans 8:26','James 5:16','Hebrews 4:16','Jeremiah 33:3'],
 prayers=[("Lord, teach me to pray","Lord Jesus, as Your disciples asked, I ask: teach me to pray. Draw me out of hurried words into real conversation. Make me hungry for time with You, more than for the things I ask.\n\nOur Father in heaven, hallowed be Your name. Your kingdom come, Your will be done in my life, my family and my nation, as it is in heaven. Give me today my daily bread. Forgive me my sins as I forgive those who sinned against me. Lead me not into temptation, but deliver me from evil.\n\nSend Your Spirit to pray through me when I have no words. Make me persistent and patient, trusting that You hear. Cleanse my heart from anything that blocks my prayers. Let my life become a prayer. In Jesus' name, Amen."),("Father, I bring others to You","Father, I stand in the gap for others. I bring to You my family, my friends, my pastor, my leaders, my neighbours and those who do not know You. I name them before You, one by one.\n\nWhere they are sick, heal. Where they are lost, find. Where they are afraid, comfort. Where they are tempted, strengthen. Send workers into the harvest. Break the chains of those who are held in darkness, and bring them into the light of Christ.\n\nGive me love that cares enough to pray, and faith that waits for Your answer. Thank You that the prayer of a righteous person is powerful and effective. Use my prayers to move mountains, and use my life to answer them. In Jesus' name, Amen.")],
 declare=["I come boldly to the throne of grace.","The Lord hears me when I call.","The Spirit helps me when I do not know what to pray.","I pray without ceasing."])

T['love'] = dict(
 doc=["The Bible does not merely say God loves; it says \"God is love\" (1 John 4:8). Love is not one of God's moods but His nature. The love He shows is agape, the Greek word for a self-giving love that chooses the other's good at its own cost. John 3:16 shows its shape: \"God so loved the world, that he gave.\" Love gives. Romans 5:8 adds, \"while we were yet sinners, Christ died for us.\" It does not wait for us to deserve it.",
 "The Hebrew word chesed, often translated lovingkindness or steadfast love or mercy, is covenant loyalty. It is love that keeps its promises. Psalm 136 repeats 26 times, \"for his mercy endureth for ever.\" The word is chesed each time. His love is not a feeling that comes and goes. It is a commitment that holds when we fail.",
 "1 Corinthians 13 is the portrait. Paul says that without love, prophecy, knowledge, faith and giving are nothing. Then he describes it with verbs: love is patient (makrothumei, long-tempered), kind, does not envy, does not boast, is not rude, does not insist on its own way, is not irritable, keeps no record of wrongs, rejoices in truth, bears, believes, hopes and endures. \"Charity never faileth.\" When you want to know whether you love, read this list and see where it presses.",
 "Jesus summed up the law: love God with all your heart, soul, mind and strength, and love your neighbour as yourself (Mark 12:30-31). He gave a new commandment: \"love one another; as I have loved you\" (John 13:34). The measure is Him. 1 John 4:19 says, \"We love him, because he first loved us.\" We do not produce love from nothing; we receive it and pass it on. Those who know they are loved can love others, even enemies (Matthew 5:44)."],
 christ="Revealed in Christ: \"Greater love hath no man than this, that a man lay down his life for his friends\" (John 15:13). He did. In Him love is not an idea but a body on a cross and a risen Lord. He washed feet, touched lepers, ate with outcasts and forgave His killers. Whatever love is, He is.",
 word="The word behind the word: in 1 Corinthians 13:4 \"suffereth long\" is makrothumei, literally long-tempered, a long fuse. Love has a long fuse. It also uses the Greek verb form for ongoing action: love keeps on being patient.",
 walk="Walk it out: Read 1 Corinthians 13:4-7 and put your own name in place of the word love. Where does it hurt? Choose one person to love in a practical way today, with a kind word, a call, or a meal. Do it without expecting anything.",
 key=['1 John 4:7-12','John 3:16','Romans 5:8','1 Corinthians 13:4-8','John 13:34-35','Romans 8:38-39','Matthew 22:37-39'],
 prayers=[("God of love, fill me","Father, You are love, and You loved me before I knew You. I thank You for Jesus, who laid down His life for me. Pour Your love into my heart by the Holy Spirit until it overflows.\n\nForgive me where I have been selfish, cold or unkind. Soften what has hardened in me. Teach me the love that is patient, the love that keeps no record of wrongs, the love that bears all things. Show me who needs a kind word, a visit, a meal or my forgiveness today.\n\nHelp me to love the difficult people, and even those who have hurt me. Let me love not only with words but in deed and in truth. And let the world know that we are Your disciples by the love we have for one another. In Jesus' name, Amen."),("Lord, help me receive Your love","Lord, I find it hard to believe that I am loved. I know the verses, but my heart does not always trust them. Make Your love real to me tonight.\n\nWhere I have been wounded by people who should have loved me, heal me. Where I have earned love by performing, free me. Let me know that nothing can separate me from Your love, not death, not life, not my failures, not my fears.\n\nRoot and ground me in love. Let me know its width, length, height and depth. Then let me share it freely, for what I have received without cost I can give without cost. In Jesus' name, Amen.")],
 declare=["God is love, and I am loved by Him.","Nothing can separate me from the love of God.","Love is patient and kind in me.","I love because He first loved me."])

T['patience'] = dict(
 doc=["Patience is one of the hardest fruits of the Spirit (Galatians 5:22), and Scripture says it is grown under pressure. The Greek makrothumia, long-temperedness, describes patience with people. The Greek hupomone, from hupo (under) and meno (remain), describes patience with circumstances: the ability to remain under a load without running away. James 1:3-4 says, \"the trying of your faith worketh patience. But let patience have her perfect work, that ye may be perfect and entire, wanting nothing.\"",
 "God is the model. Exodus 34:6 describes Him as \"slow to anger.\" The Hebrew is erek apayim, long of nostrils: a long breath before anger. 2 Peter 3:9 says He is longsuffering toward us, not willing that any should perish. The delay we sometimes resent in His promises is mercy giving time. So patience grows as we remember how patient He has been with us.",
 "Waiting is often where God does His best work. Abraham waited twenty-five years for Isaac. Joseph waited thirteen years from the pit to the palace. Moses spent forty years in the desert. David waited years between the anointing and the throne. Habakkuk 2:3 says that the vision \"will surely come, it will not tarry\" and in the meantime \"wait for it.\" Waiting is not wasted; it is a workshop. Psalm 37:7 says, \"Rest in the Lord, and wait patiently for him.\"",
 "Impatience reaches for shortcuts, and shortcuts cost: Abraham took Hagar, Saul offered the sacrifice himself, Moses struck the rock. Patience trusts God's timing and God's way. It also shows up in daily life: in traffic, in queues, in children, in marriage, in slow growth. Patience is love that refuses to hurry another person's change. Ask for it, practice it, and thank God for the situations that train it."],
 christ="Revealed in Christ: \"Consider him that endured such contradiction of sinners against himself, lest ye be wearied and faint in your minds\" (Hebrews 12:3). He endured the cross, despising the shame. He waited thirty years before He began His ministry. He is patient with your slow progress, and He teaches you to be patient with others.",
 word="The word behind the word: hupomone is \"remaining under.\" It is the patience of a person who carries a load without throwing it down. It is the opposite of escaping, and it is used of the endurance of the saints (Revelation 14:12).",
 walk="Walk it out: Name the situation in which you are most impatient. Ask God what He is doing in you while you wait. Do not take a shortcut today. Practice slowing down: breathe before you answer, and let the other person finish.",
 key=['James 1:2-4','Psalms 37:7-9','Galatians 5:22-23','Romans 8:25','Isaiah 40:31','Habakkuk 2:3','Hebrews 12:1-2'],
 prayers=[("Lord, grow patience in me","Father, I confess that I am impatient. I want things now, and I want people to change now. Forgive me for the times I have snapped, rushed or taken shortcuts. Thank You for being slow to anger and rich in mercy toward me.\n\nPlant in me the fruit of patience. Teach me to remain under the pressure without running. Let me trust Your timing, which is never late. Where I am waiting for an answer, a door, a healing or a change, hold me steady.\n\nGive me the long fuse of love for the people around me. Let me listen before I speak and bless before I react. Make me like Jesus, who endured and did not give up. In Jesus' name, Amen."),("Father, while I wait","Father, I have been waiting a long time, and I am tired. I believe You are working, even when I cannot see it. Strengthen my heart. Let me not grow weary in doing good, for in due season I will reap if I do not faint.\n\nProtect me from bitterness and from doing things in my own way. Remind me of those who waited before me and were not disappointed. Use this season to deepen my roots.\n\nI rest in You and wait patiently. I trust that Your timing is perfect. Let me keep serving, praying and hoping until the answer comes. In Jesus' name, Amen.")],
 declare=["The Lord is patient with me and I am patient with others.","I wait on the Lord and He renews my strength.","In due season I will reap if I do not faint.","God's timing is perfect."])

T['conflict'] = dict(
 doc=["Conflict is part of life among people, and the Bible does not hide it. The early church had disputes, Paul and Barnabas split over Mark, and Jesus gave a whole process for dealing with it (Matthew 18:15-17). The question is not whether conflict comes but how we handle it. Romans 12:18 says, \"If it be possible, as much as lieth in you, live peaceably with all men.\" Notice the two limits: if it is possible, and as much as depends on you. You are responsible for your part only.",
 "Jesus gave a clear order. First, go to the person privately: \"tell him his fault between thee and him alone.\" Not to the group chat, not to the neighbours. If that fails, take one or two others. Only after that, the church. The aim, in the Lord's words, is \"thou hast gained thy brother.\" The goal is restoration, not victory. Before you go, Matthew 7:3-5 says to take the log out of your own eye first, so you can see clearly.",
 "Proverbs gives wisdom for the tongue: \"A soft answer turneth away wrath: but grievous words stir up anger\" (15:1). \"He that answereth a matter before he heareth it, it is folly and shame unto him\" (18:13). James 1:19 says, \"swift to hear, slow to speak, slow to wrath.\" Ephesians 4:26 permits anger but limits it: \"Be ye angry, and sin not: let not the sun go down upon your wrath.\" Truth must be spoken, but in love (Ephesians 4:15).",
 "Jesus said, \"Blessed are the peacemakers: for they shall be called the children of God\" (Matthew 5:9). The Greek eirenopoios means one who makes peace, an active role, not just one who avoids trouble. The peacemaker is not the peace-keeper who hides issues, but the one who brings reconciliation. And Matthew 5:23-24 says if you remember that someone has something against you, go first to be reconciled, before you bring your gift. Peace between people matters to God as much as worship."],
 christ="Revealed in Christ: \"He is our peace, who hath made both one, and hath broken down the middle wall of partition\" (Ephesians 2:14). The cross reconciled us to God and to each other. When He was reviled, He did not revile again (1 Peter 2:23). On the cross He prayed, \"Father, forgive them.\" His way of handling conflict is the way of the cross.",
 word="The word behind the word: eirenopoios, peacemaker, is made of eirene (peace) and poieo (to make). The same poieo gives us poiema, workmanship. Peacemakers are craftsmen: they construct peace with patient hands.",
 walk="Walk it out: Think of one unresolved conflict. Pray for the person by name for a week. Ask what your part is. Then take the first step privately: a message, a call or a visit. Begin with, \"I value you, and I want us to be well.\"",
 key=['Matthew 18:15','Matthew 5:23-24','Romans 12:17-21','Proverbs 15:1','James 1:19-20','Ephesians 4:26-27','Ephesians 4:31-32'],
 prayers=[("Lord, make me a peacemaker","Father, You sent Your Son to reconcile us to You, and You gave us the ministry of reconciliation. I bring to You a broken or strained relationship. You know the details, and You know my part.\n\nShow me where I have been wrong and give me humility to admit it. Take pride, defensiveness and the need to win out of my heart. Give me a soft answer, a listening ear and courage to speak the truth in love.\n\nMove in the heart of the other person. Soften what is hard. Open a door to talk. Bring healing where there is hurt. And if reconciliation is not yet possible, keep me from bitterness and keep me at peace as far as it depends on me. Make me a peacemaker, called a child of God. In Jesus' name, Amen."),("Father, protect our unity","Lord, You prayed that we may be one. I ask You to protect the unity of my family, my church and my workplace. Expose every whisper, division and offence that Satan uses.\n\nWhere I have spoken carelessly, forgive me. Where I have been hurt, heal me. Give me the grace to forgive quickly and to ask forgiveness quickly. Help me to see people as You see them, as people for whom Christ died.\n\nLet Your peace rule in our hearts. Let us bear with one another in love, and let the world see Christ in how we treat each other. In Jesus' name, Amen.")],
 declare=["Blessed are the peacemakers; I am a child of God.","I speak the truth in love.","I forgive quickly and I seek peace.","Christ is my peace."])

T['salvation'] = dict(
 doc=["Salvation is the heart of the Gospel, and it is a gift. Ephesians 2:8-9 says, \"For by grace are ye saved through faith; and that not of yourselves: it is the gift of God: not of works, lest any man should boast.\" The Greek charis (grace) is unearned favour, and doron (gift) is something given freely. You cannot buy it, earn it or deserve it. You can only receive it.",
 "Why do we need it? Romans 3:23 says, \"all have sinned, and come short of the glory of God.\" Romans 6:23 adds, \"the wages of sin is death; but the gift of God is eternal life through Jesus Christ our Lord.\" Sin is not only bad behaviour, it is a break in relationship with the holy God, and the penalty is separation from Him. No amount of good deeds can repair it. That is why God Himself acted.",
 "The cross is God's answer. 2 Corinthians 5:21 says, \"He hath made him to be sin for us, who knew no sin; that we might be made the righteousness of God in him.\" This is the great exchange: our sin to Him, His righteousness to us. Romans 5:8 says God shows His love in that Christ died for us while we were still sinners. The resurrection proves that the payment was accepted and that death is defeated (1 Corinthians 15:3-4, 20).",
 "How do we receive it? Romans 10:9-10 says, \"if thou shalt confess with thy mouth the Lord Jesus, and shalt believe in thine heart that God hath raised him from the dead, thou shalt be saved.\" Repent, which means turn around, and believe. The Greek sozo means to save, rescue and make whole. Salvation has a past (we were saved), a present (we are being saved) and a future (we will be saved). It begins a new life, led by the Spirit, lived in community, and growing in obedience. Assurance comes from God's promise: \"These things have I written unto you that believe on the name of the Son of God; that ye may know that ye have eternal life\" (1 John 5:13)."],
 christ="Revealed in Christ: the name Jesus is the Greek form of Yeshua, which means \"the Lord saves\" (Matthew 1:21). He is not only the teacher of the way, He is the way (John 14:6). \"Neither is there salvation in any other: for there is none other name under heaven given among men, whereby we must be saved\" (Acts 4:12).",
 word="The word behind the word: sozo is the same verb used for forgiven, healed, delivered and rescued from drowning. When Peter sank and cried, \"Lord, save me\" (Matthew 14:30), he used sozo. Salvation is that cry answered by a hand.",
 walk="Walk it out: If you have never given your life to Christ, you can do it now, with a simple honest prayer. If you have, thank Him, and tell one person this week what He has done for you. Find a church or fellowship to grow in, and read the Gospel of John.",
 key=['Ephesians 2:8-9','John 3:16-17','Romans 10:9-13','Romans 6:23','Acts 4:12','2 Corinthians 5:17-21','1 John 5:11-13'],
 prayers=[("A prayer to receive Christ","Lord Jesus, I come to You as I am. I confess that I have sinned and fallen short of Your glory. I am sorry, and I turn from my sins. I believe that You are the Son of God, that You died on the cross for my sins, and that God raised You from the dead.\n\nI receive Your forgiveness. I invite You to be my Saviour and my Lord. Come into my life, make me new, fill me with Your Holy Spirit. Write my name in the book of life. Thank You that I am a child of God, forgiven and loved, not by my works but by Your grace.\n\nHelp me to follow You every day. Lead me to Your Word and to Your people. Give me courage to tell others. I give You my life. In Jesus' name, Amen."),("Thank You for saving me","Father, I thank You for the gift of salvation. Thank You that while I was far from You, Christ died for me. Thank You that I was lost and am found, blind and now see, dead and now alive.\n\nHelp me to live worthy of this gift, not to earn it but to honour it. Keep me from going back to my old ways. Where I doubt my salvation, assure me by Your Word and Your Spirit. Where I am weak, lift me.\n\nMake me a witness. Bring to my mind the people who do not know You, and give me love, words and opportunities. Let the whole earth hear of the Saviour. All glory to You, Father, Son and Holy Spirit, now and forever. In Jesus' name, Amen.")],
 declare=["I am saved by grace through faith.","Jesus Christ is my Lord and Saviour.","I have passed from death to life.","Nothing can snatch me out of the Father's hand."])
