const { chromium } = require('playwright');
let fail=0; const ck=(n,c)=>{ console.log((c?'  ok   ':'  FAIL ')+n); if(!c){fail++;} };
(async()=>{ const b=await chromium.launch(); const ctx=await b.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}); const p=await ctx.newPage(); const errs=[]; p.on('pageerror',e=>errs.push(e.message));
 await require('./biz_boot.js')(p,{demo:true});
 await p.waitForFunction(()=>{ const r=window.__t.State.ready; return r.products&&r.sales&&r.users&&r.tills&&r.messages&&r.accountingPeriods; });
 await p.evaluate(async()=>{
   const t=window.__t, r=t.refs, now=Date.now(), iso=x=>new Date(x).toISOString();
   const beer = await r.products.add({ name:'Castle Lager 340ml', sellPrice:20, costPrice:15, stockQty:0, taxCategory:'EXEMPT', createdAt:iso(now) });
   const bid = beer.id || (beer.doc && beer.doc.id);
   const prods = t.State.products; const b1 = prods.find(x=>x.name.indexOf('Castle')===0);
   const bi = { productId:b1.id, name:'Castle Lager 340ml', qty:2, unitPrice:10, cost:15 };
   for(let i=0;i<3;i++) await r.sales.add({ items:[bi], total:20, paymentMethod:'cash', createdAt:iso(now-i*3600000) });
   const lm = new Date(); lm.setDate(1); lm.setMonth(lm.getMonth()-1); lm.setDate(10);
   await r.sales.add({ items:[{productId:b1.id,name:'Bread',qty:1,unitPrice:10,cost:5}], total:10, paymentMethod:'cash', createdAt:lm.toISOString() });
   for(let i=0;i<2;i++) await r.tills.add({ status:'closed', cashierName:'Sam', variance:-25, openedAt:iso(now-86400000*(i+1)), closedAt:iso(now-86400000*(i+1)+3600000) });
   for(let i=0;i<4;i++) t.logAudit('delete','product',null,'Removed item '+i);
 });
 await p.waitForTimeout(800);
 await p.evaluate(()=>window.__t.agentTick('test')); await p.waitForTimeout(2500);
 const r = await p.evaluate(()=>{ const t=window.__t, S=t.State; return { kinds:S.agentNotes.map(n=>n.kind+':'+n.level), titles:S.agentNotes.map(n=>n.title), msgs:S.messages.filter(m=>m.fromId==='pesa-ai').length, periods:S.accountingPeriods.length, alerts:t.smartAlerts().filter(a=>/^agent-/.test(a.id)).length, dash:S.agentNotes.some(n=>/[-‐-―−–—]/.test(n.title.replace(/[A-Za-z]+-[0-9a-z]+/,'')) ) }; });
 console.log(r);
 ck('reorder draft note', r.kinds.some(k=>k.startsWith('reorder')));
 ck('risk warnings raised (shortage, deletions, exempt, below cost)', r.kinds.filter(k=>k.startsWith('risk')).length>=4);
 ck('monthly pack filed by the accountant', r.periods>=1 && r.kinds.some(k=>k.startsWith('accounts')));
 ck('messages sent as Pesa AI Assistant', r.msgs>=3);
 ck('notes show in the Alert centre', r.alerts>=2);
 const again = await p.evaluate(async()=>{ const t=window.__t, n0=t.State.agentNotes.length, m0=t.State.messages.length; t.agentTick('again'); await new Promise(x=>setTimeout(x,1500)); return [n0,t.State.agentNotes.length,m0,t.State.messages.length]; });
 ck('running again adds no duplicates', again[0]===again[1] && again[2]===again[3]);
 await p.evaluate(()=>window.__t.openAgentSheet()); await p.waitForTimeout(300);
 ck('assistant page opens', (await p.evaluate(()=>document.body.innerText)).indexOf('Pesa AI Assistant')>-1);
 // the assistant understands requests and only changes things after Confirm
 const cmd = await p.evaluate(async()=>{ const t=window.__t, S=t.State, r=t.refs; const out={};
   await r.users.add({ name:'Sam Tiger', role:'cashier', active:true, createdAt:new Date().toISOString() });
   await new Promise(x=>setTimeout(x,500));
   const prod = S.products.find(x=>x.name==='Milk 1L'); const q0 = prod.stockQty;
   const E=S.expenses.length, P=S.products.length, M=S.messages.length;
   const a = t.agentParse('add expense 150 for transport'); out.exp=[!!a.confirm, a.text, S.expenses.length===E]; await a.confirm(); await new Promise(x=>setTimeout(x,400)); out.exp.push(S.expenses.length===E+1);
   const b = t.agentParse('add product Bread price 18 cost 12 stock 20'); out.prod=[!!b.confirm, b.text]; await b.confirm(); await new Promise(x=>setTimeout(x,400)); out.prod.push(S.products.length===P+1);
   const c = t.agentParse('add 20 to the stock of milk 1l'); out.stock=[!!c.confirm, c.text]; await c.confirm(); await new Promise(x=>setTimeout(x,400)); out.stock.push(S.products.find(x=>x.name==='Milk 1L').stockQty===q0+20);
   const d = t.agentParse('set price of milk 1l to 30'); out.price=[!!d.confirm]; await d.confirm(); await new Promise(x=>setTimeout(x,400)); out.price.push(S.products.find(x=>x.name==='Milk 1L').sellPrice===30);
   const e = t.agentParse('tell Sam to count the till before closing'); out.msg=[!!e.confirm, e.text]; await e.confirm(); await new Promise(x=>setTimeout(x,400)); out.msg.push(S.messages.length===M+1 && S.messages[0].toName==='Sam Tiger' || S.messages.some(m=>m.toName==='Sam Tiger'));
   out.nav = t.agentParse('open accountant'); out.del = t.agentParse('delete all sales'); out.q = t.agentParse('how much did I sell today?'); out.junk = t.agentParse('zzzz qqqq xxxx yyyy');
   out.noConfirmNoChange = (()=>{ const n=S.expenses.length; t.agentParse('add expense 999 for rent'); return n===S.expenses.length; })();
   return out; });
 console.log(JSON.stringify(cmd).slice(0,900));
 ck('expense: asks first, then records', cmd.exp[0] && cmd.exp[2] && cmd.exp[3]);
 ck('add product after confirm', cmd.prod[0] && cmd.prod[2]);
 ck('add stock after confirm', cmd.stock[0] && cmd.stock[2]);
 ck('change price after confirm', cmd.price[0] && cmd.price[1]);
 ck('message to a named employee', cmd.msg[0] && cmd.msg[2]);
 ck('opens a page', cmd.nav.page==='accountant');
 ck('refuses to delete records', /password/.test(cmd.del.text) && !cmd.del.confirm);
 ck('answers a question', !!cmd.q.text && !/did not understand/.test(cmd.q.text));
 ck('unknown request is handled', /did not understand/.test(cmd.junk.text));
 ck('nothing changes without Confirm', cmd.noConfirmNoChange);
 await p.evaluate(()=>window.__t.closeModal()); await p.evaluate(()=>document.getElementById('menuBtn').click()); await p.waitForTimeout(300);
 await p.evaluate(()=>document.querySelector('.drawer-row[data-drawer-row="hub-tools"]').click()); await p.waitForTimeout(500);
 ck('the Smart tools page has its own Pesa AI Assistant row with its icon', await p.evaluate(()=>!!document.querySelector('[data-drawer-row="agent"] img')));
 ck('no page errors', errs.length===0); if(errs.length) console.log(errs.slice(0,3));
 await b.close(); console.log(fail?'FAILED '+fail:'ALL OK'); process.exit(fail?1:0);
})();
