const { chromium } = require('playwright');
let fail=0; const ck=(n,c)=>{ console.log((c?'  ok   ':'  FAIL ')+n); if(!c){fail++;} };
(async()=>{ const b=await chromium.launch(); const ctx=await b.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}); const p=await ctx.newPage(); const errs=[]; p.on('pageerror',e=>errs.push(e.message));
 await require('./biz_boot.js')(p,{demo:true});
 await p.waitForFunction(()=>{ const r=window.__t.State.ready; return r.products&&r.sales&&r.users&&r.tills&&r.messages&&r.accountingPeriods; });
 await p.evaluate(async()=>{
   const t=window.__t, r=t.refs, now=Date.now(), iso=x=>new Date(x).toISOString();
   const beer = await r.products.add({ name:'Castle Lager 340ml', sellPrice:20, costPrice:15, stockQty:0, taxCategory:'EXEMPT', createdAt:iso(now) });
   const bid = beer.id || (beer.doc && beer.doc.id);
   const prods = t.State.products; const b1 = prods.find(x=>x.name.indexOf('Castle')===0);
   const bi = { productId:b1.id, name:'Castle Lager 340ml', qty:2, unitPrice:10, cost:15 };
   for(let i=0;i<3;i++) await r.sales.add({ items:[bi], total:20, paymentMethod:'cash', createdAt:iso(now-i*3600000) });
   const lm = new Date(); lm.setDate(1); lm.setMonth(lm.getMonth()-1); lm.setDate(10);
   await r.sales.add({ items:[{productId:b1.id,name:'Bread',qty:1,unitPrice:10,cost:5}], total:10, paymentMethod:'cash', createdAt:lm.toISOString() });
   for(let i=0;i<2;i++) await r.tills.add({ status:'closed', cashierName:'Sam', variance:-25, openedAt:iso(now-86400000*(i+1)), closedAt:iso(now-86400000*(i+1)+3600000) });
   for(let i=0;i<4;i++) t.logAudit('delete','product',null,'Removed item '+i);
 });
 await p.waitForTimeout(800);
 await p.evaluate(()=>window.__t.agentTick('test')); await p.waitForTimeout(2500);
 const r = await p.evaluate(()=>{ const t=window.__t, S=t.State; return { kinds:S.agentNotes.map(n=>n.kind+':'+n.level), titles:S.agentNotes.map(n=>n.title), msgs:S.messages.filter(m=>m.fromId==='pesa-ai').length, periods:S.accountingPeriods.length, alerts:t.smartAlerts().filter(a=>/^agent-/.test(a.id)).length, dash:S.agentNotes.some(n=>/[-‐-―−–—]/.test(n.title.replace(/[A-Za-z]+-[0-9a-z]+/,'')) ) }; });
 console.log(r);
 ck('reorder draft note', r.kinds.some(k=>k.startsWith('reorder')));
 ck('risk warnings raised (shortage, deletions, exempt, below cost)', r.kinds.filter(k=>k.startsWith('risk')).length>=4);
 ck('monthly pack filed by the accountant', r.periods>=1 && r.kinds.some(k=>k.startsWith('accounts')));
 ck('messages sent as Pesa AI Assistant', r.msgs>=3);
 ck('notes show in the Alert centre', r.alerts>=2);
 const again = await p.evaluate(async()=>{ const t=window.__t, n0=t.State.agentNotes.length, m0=t.State.messages.length; t.agentTick('again'); await new Promise(x=>setTimeout(x,1500)); return [n0,t.State.agentNotes.length,m0,t.State.messages.length]; });
 ck('running again adds no duplicates', again[0]===again[1] && again[2]===again[3]);
 await p.evaluate(()=>window.__t.openAgentSheet()); await p.waitForTimeout(300);
 ck('assistant page opens', (await p.evaluate(()=>document.body.innerText)).indexOf('Pesa AI Assistant')>-1);
 await p.evaluate(()=>window.__t.closeModal()); await p.evaluate(()=>document.getElementById('menuBtn').click()); await p.waitForTimeout(300);
 ck('menu has its own Pesa AI Assistant row', await p.evaluate(()=>!!document.querySelector('[data-drawer-row="agent"] img')));
 ck('no page errors', errs.length===0); if(errs.length) console.log(errs.slice(0,3));
 await b.close(); console.log(fail?'FAILED '+fail:'ALL OK'); process.exit(fail?1:0);
})();
