const { chromium } = require('playwright');
let fail=0; const ck=(n,c,x)=>{ console.log((c?'  ok   ':'  FAIL ')+n+(!c&&x!==undefined?'  -> '+JSON.stringify(x).slice(0,300):'')); if(!c) fail++; };
(async()=>{
 const b=await chromium.launch(); const ctx=await b.newContext({viewport:{width:412,height:915},serviceWorkers:'block'}); const p=await ctx.newPage(); const errs=[]; p.on('pageerror',e=>errs.push(e.message));
 await require('./biz_boot.js')(p);
 const r=await p.evaluate(()=>{ const T=window.__t, S=T.State, DAY=86400000, now=Date.now();
  const mk=(id,name,sell,cost,stock,extra)=>Object.assign({id,name,sellPrice:sell,costPrice:cost,stockQty:stock,category:'G',createdAt:new Date(now-120*DAY).toISOString()},extra||{});
  S.products=[mk('p1','Brown Bread',20,12,6),mk('p2','Milk 1L',18,14,80),mk('p3','Dusty Tin',10,6,40),mk('p4','Cheap Sweet',5,4.8,100),mk('p5','Butter',30,20,50)];
  S.customers=[{id:'c1',name:'Mama Selma',balance:450,createdAt:new Date(now-90*DAY).toISOString()}];
  S.expenses=[{id:'e1',amount:120,createdAt:new Date(now-3600000).toISOString()}];
  S.sales=[]; let n=0; const sale=(daysAgo,hour,items)=>{ const d=new Date(now-daysAgo*DAY); d.setHours(hour,0,0,0); const tot=items.reduce((a,i)=>a+i.unitPrice*i.qty,0), cost=items.reduce((a,i)=>a+i.cost*i.qty,0); S.sales.push({id:'s'+(n++),createdAt:d.toISOString(),total:tot,cost,paymentMethod:'cash',items:items.map(i=>({productId:i.id,name:i.name,qty:i.qty,unitPrice:i.unitPrice,lineTotal:i.unitPrice*i.qty,cost:i.cost}))}); };
  const bread={id:'p1',name:'Brown Bread',unitPrice:20,cost:12}, milk={id:'p2',name:'Milk 1L',unitPrice:18,cost:14}, butter={id:'p5',name:'Butter',unitPrice:30,cost:20};
  for(let d=1;d<=27;d++){ sale(d,9,[Object.assign({qty:2},bread),Object.assign({qty:1},milk)]); sale(d,10,[Object.assign({qty:1},bread),Object.assign({qty:1},milk)]); }
  for(let d=0;d<=3;d++) sale(d,8,[Object.assign({qty:6},butter)]);
  S.ready.sales=true; S.ready.products=true;
  const out={};
  out.brief=T.brainBriefing().map(x=>x.id+': '+x.text);
  out.dead=T.brainDeadStock(45).map(x=>x.product.name);
  out.thin=T.brainThinMargin().map(x=>x.product.name);
  out.trend=T.brainTrends();
  out.tog=T.brainTogether([{productId:'p1'}],3).map(x=>x.name);
  out.togNone=T.brainTogether([{productId:'p3'}],3).length;
  out.a1=T.brainAnswer('how much did I sell yesterday?');
  out.a2=T.brainAnswer('who owes me money');
  out.a3=T.brainAnswer('how many bread do I have');
  out.a4=T.brainAnswer('what should I reorder');
  out.a5=T.brainAnswer('profit this week');
  out.a6=T.brainAnswer('what is not selling');
  out.a7=T.brainAnswer('best sellers');
  out.a8=T.brainAnswer('blah blah xyzzy');
  out.a9=T.brainAnswer('expenses today');
  out.alerts=T.brainAlerts().map(x=>x.id);
  out.card=T.brainCardHtml().length;
  return out; });
 console.log(JSON.stringify(r.brief,null,1));
 ck('briefing has several items', r.brief.length>=3, r.brief);
 ck('reorder: bread running out', r.brief.some(x=>/^reorder: Brown Bread/.test(x)), r.brief);
 ck('late customer flagged', r.brief.some(x=>/^late/.test(x)), r.brief);
 ck('dead stock finds Dusty Tin only', r.dead.length===2 && r.dead.indexOf('Dusty Tin')>-1 && r.dead.indexOf('Brown Bread')<0, r.dead);
 ck('thin margin finds Cheap Sweet', r.thin[0]==='Cheap Sweet', r.thin);
 ck('butter trending up', r.trend.up.some(x=>x.name==='Butter'), r.trend);
 ck('together: milk goes with bread', r.tog[0]==='Milk 1L', r.tog);
 ck('together: nothing for unsold item', r.togNone===0);
 ck('answer yesterday sales', /Sales for yesterday: .*3[0-9]|Sales for yesterday/.test(r.a1.text) && /3 sales|2 sales/.test(r.a1.text), r.a1);
 ck('answer who owes', /450/.test(r.a2.text)&&/Selma/.test(r.a2.lines[0]), r.a2);
 ck('answer stock of bread', /Brown Bread/.test(r.a3.text+(r.a3.lines||[]).join())&&/6/.test((r.a3.lines||[]).join()), r.a3);
 ck('answer reorder', /Brown Bread/.test((r.a4.lines||[]).join()), r.a4);
 ck('answer profit', /Profit for the last 7 days/.test(r.a5.text), r.a5);
 ck('answer not selling', /Dusty Tin/.test((r.a6.lines||[]).join()), r.a6);
 ck('answer best sellers', /Brown Bread|Milk/.test((r.a7.lines||[]).join()), r.a7);
 ck('answer unknown is polite', /did not understand/.test(r.a8.text), r.a8);
 ck('answer expenses', /120/.test(r.a9.text), r.a9);
 ck('alerts include margin', r.alerts.indexOf('thinmargin')>-1, r.alerts);
 ck('sell card renders', r.card>50);
 // UI: open sheet, ask, check answer
 await p.evaluate(()=>window.__t.openBrainSheet()); await p.waitForSelector('#brQ');
 await p.fill('#brQ','who owes me'); await p.click('#brGo');
 const t=await p.textContent('#brAns'); ck('sheet shows an answer', /450/.test(t), t);
 await p.evaluate(()=>{ window.__t.closeModal(); const T=window.__t; T.State.cart=[{productId:'p1',name:'Brown Bread',unitPrice:20,cost:12,qty:1,unit:'',maxQty:6}]; T.openCartSheet(); });
 await p.waitForSelector('[data-br-add]'); await p.click('[data-br-add]');
 const cart=await p.evaluate(()=>window.__t.State.cart.map(c=>c.name)); ck('tap suggestion adds to cart', cart.indexOf('Milk 1L')>-1, cart);
 // speed with 30000 sales
 const ms=await p.evaluate(()=>{ const T=window.__t,S=T.State,now=Date.now(); const base=S.sales.slice(); for(let i=0;i<30000;i++){ S.sales.push({id:'x'+i,createdAt:new Date(now-(i%60)*86400000).toISOString(),total:50,cost:30,items:[{productId:'p'+(1+i%5),name:'x',qty:1,lineTotal:50,cost:30},{productId:'p'+(1+(i+1)%5),name:'y',qty:1,lineTotal:50,cost:30}]}); } const t0=performance.now(); T.brainBriefing(); T.brainAnswer('best sellers'); return performance.now()-t0; });
 ck('briefing on 30000 sales under 1500ms', ms<1500, ms);
 ck('no page errors', errs.length===0, errs);
 await b.close(); console.log(fail?'FAILED '+fail:'ALL OK'); process.exit(fail?1:0);
})();
