const { chromium } = require('playwright');
let fail=0; const ck=(n,c)=>{ console.log((c?'  ok   ':'  FAIL ')+n); if(!c){fail++;} };
(async()=>{ const b=await chromium.launch(); const ctx=await b.newContext({viewport:{width:390,height:844},serviceWorkers:'block',acceptDownloads:true}); const p=await ctx.newPage(); const errs=[]; p.on('pageerror',e=>errs.push(e.message));
 await require('./biz_boot.js')(p);
 await p.evaluate(()=>{ window.__opened=[]; window.open=function(u){ window.__opened.push(String(u)); return null; }; });
 await p.evaluate(()=>window.__t.openSendSheet({ title:'Send invoice', subject:'Invoice INV-1 from Test', emailBody:(n,f)=>'Hello '+n+', please find the invoice.', shortText:()=>'Invoice', buildFile:async()=>new File(['%PDF-1.4 test'],'invoice-INV-1.pdf',{type:'application/pdf'}), audit:{label:'Invoice INV-1'} }));
 await p.waitForSelector('[data-channel="gmail"]');
 ck('the send sheet has a Gmail button', await p.isVisible('[data-channel="gmail"]'));
 await p.fill('#sdEmail','someone@gmail.com, other@example.com');
 const dl = p.waitForEvent('download',{timeout:8000}).catch(()=>null);
 await p.click('[data-channel="gmail"]'); const d = await dl; await p.waitForTimeout(600);
 const u = await p.evaluate(()=>window.__opened.slice(-1)[0]||'');
 console.log(u.slice(0,200));
 ck('opens a Gmail message in the browser', /^https:\/\/mail\.google\.com\/mail\/\?view=cm/.test(u));
 ck('address, subject and text are filled in', /to=someone%40gmail\.com%2Cother%40example\.com/.test(u) && /su=Invoice%20INV-1/.test(u) && /body=Hello/.test(u));
 ck('the PDF is saved so it can be attached', !!d && /invoice-INV-1\.pdf/.test(d.suggestedFilename()));
 ck('it tells the person how to attach it', /paperclip/i.test(await p.evaluate(()=>document.querySelector('#sdResult').innerText)));
 await p.fill('#sdEmail','not an email'); await p.click('[data-channel="gmail"]'); await p.waitForTimeout(300);
 ck('a bad address is refused', await p.evaluate(()=>window.__opened.length===1));
 ck('no page errors', errs.length===0); if(errs.length) console.log(errs.slice(0,3));
 await b.close(); console.log(fail?'FAILED '+fail:'ALL OK'); process.exit(fail?1:0);
})();
