const { chromium } = require('playwright');
let fail=0; const ck=(n,c)=>{ console.log((c?'  ok   ':'  FAIL ')+n); if(!c){fail++;} };
(async()=>{ const b=await chromium.launch(); const ctx=await b.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}); const p=await ctx.newPage(); const errs=[]; p.on('pageerror',e=>errs.push(e.message));
 await require('./biz_boot.js')(p);
 await p.evaluate(()=>window.__t.setTab('stock')); await p.waitForSelector('#mockStrip');
 const sizes = await p.evaluate(()=>[...document.querySelectorAll('#mockN option')].map(o=>+o.value));
 ck('offers up to 100,000 test products', sizes.indexOf(100000)>-1 && sizes.indexOf(10000)>-1);
 await p.click('#mockStrip summary'); await p.selectOption('#mockN','100000'); await p.click('[data-mock="load"]');
 await p.waitForFunction(()=>window.__t.State.products.filter(x=>x.isMock).length===100000,null,{timeout:60000});
 await p.waitForTimeout(400);
 ck('100,000 test products loaded from the Stock page', await p.evaluate(()=>window.__t.State.products.length===100000));
 ck('the Stock page shows the loaded count and a remove button', await p.evaluate(()=>/100,000/.test(document.getElementById('mockStrip').innerText) && !!document.querySelector('[data-mock="remove"]')));
 const s = await p.evaluate(()=>{ const t=window.__t; const a=performance.now(); const l=t.searchProducts(t.State.products,'maize meal'); const ms=performance.now()-a; const bc=t.State.products[99999].barcode; return { hits:l.length, ms:Math.round(ms), bcHit:t.searchProducts(t.State.products,bc)[0]===t.State.products[99999] }; });
 console.log(s); ck('search and barcode lookup work on 100,000', s.hits>0 && s.bcHit && s.ms<1500);
 ck('they are test products only, not real stock', await p.evaluate(()=>window.__t.State.products.every(x=>x.isMock)));
 await p.click('[data-mock="remove"]'); await p.waitForTimeout(500);
 ck('removing clears them', await p.evaluate(()=>window.__t.State.products.length===0));
 ck('no page errors', errs.length===0); if(errs.length) console.log(errs.slice(0,3));
 await b.close(); console.log(fail?'FAILED '+fail:'ALL OK'); process.exit(fail?1:0);
})();
