const { chromium } = require('playwright');
let fail=0; const ck=(n,c,x)=>{ console.log((c?'  ok   ':'  FAIL ')+n+(!c&&x!==undefined?'  -> '+JSON.stringify(x).slice(0,300):'')); if(!c) fail++; };
(async()=>{
 const b=await chromium.launch(); const ctx=await b.newContext({viewport:{width:412,height:915},serviceWorkers:'block'}); const p=await ctx.newPage(); const errs=[]; p.on('pageerror',e=>errs.push(e.message));
 await p.goto('http://localhost:8933/index.html'); await p.waitForSelector('#rcCompanyName');
 await p.fill('#rcCompanyName','NP'); await p.fill('#rcOwnerName','A'); await p.fill('#rcOwnerEmail','a@x.com'); await p.fill('#rcOwnerPassword','aaaa1111'); await p.fill('#rcOwnerPassword2','aaaa1111'); await p.click('#rcSubmit');
 await p.waitForSelector('#cnAgree'); await p.click('#cnAgree'); await p.click('#cnAccept'); await p.waitForSelector('.hero-card'); await p.evaluate(()=>{ try{ window.__t.btSave({ setupHidden:true }); window.__t.pfSave({ remindAt:Date.now() }); }catch(e){} });
 const sp=await p.evaluate(()=>{const f=window.__t.splitPriceFromName; return [f('1. Polana Maize Meal (3kg): N$ 79.99'),f('Bread'),f('Milk - N$ 19.95'),f('Samp (1kg) N$16.00'),f('10. Bokomo Corn Flakes (1kg): N$ 69.90'),f('Rice 2kg')];});
 ck('splits "Polana … N$ 79.99"', sp[0].name==='Polana Maize Meal (3kg)' && sp[0].price===79.99, sp[0]);
 ck('plain name untouched', sp[1].name==='Bread' && sp[1].price===null && !sp[1].changed, sp[1]);
 ck('dash form', sp[2].name==='Milk' && sp[2].price===19.95, sp[2]);
 ck('no space form', sp[3].name==='Samp (1kg)' && sp[3].price===16, sp[3]);
 ck('list number removed', sp[4].name==='Bokomo Corn Flakes (1kg)' && sp[4].price===69.9, sp[4]);
 ck('weights are not prices', sp[5].price===null && sp[5].name==='Rice 2kg', sp[5]);
 const imp=await p.evaluate(()=>window.__t.parseCsvText('Name,Qty\n"2. Tastic Rice (2kg): N$ 34.99",50\nSugar,5').rows.map(r=>[r.name,r.sellPrice]));
 ck('csv import moves the price', imp[0][0]==='Tastic Rice (2kg)' && imp[0][1]===34.99 && imp[1][1]===0, imp);
 await p.evaluate(async()=>{const T=window.__t; await T.refs.products.doc('a').set({name:'1. Polana Maize Meal (3kg): N$ 79.99',sellPrice:0,costPrice:0,stockQty:50,category:'Food'}); await T.refs.products.doc('b').set({name:'Bread',sellPrice:15,costPrice:5,stockQty:10}); await T.refs.products.doc('c').set({name:'Eggs (18): N$ 61.99',sellPrice:0,stockQty:50}); await T.refs.products.doc('d').set({name:'Milk: N$ 19.95',sellPrice:22,stockQty:50}); T.setTab('sell');});
 await p.waitForTimeout(500);
 ck('banner counts 2 products', /2\s+products have their price written/.test(await p.innerText('#content')), await p.innerText('#content'));
 await p.click('#fixNamePrices'); await p.waitForTimeout(400);
 const btn=await p.$$eval('button',a=>a.map(x=>x.innerText).filter(t=>/^Fix \d/.test(t))); ck('confirm button offered', btn.length>0, btn);
 await p.locator('button',{hasText:/^Fix 2/}).last().click(); await p.waitForTimeout(1500);
 const after=await p.evaluate(()=>window.__t.State.products.map(x=>[x.id,x.name,x.sellPrice,x.stockQty]).sort());
 ck('names tidied, prices set, stock kept', JSON.stringify(after)===JSON.stringify([['a','Polana Maize Meal (3kg)',79.99,50],['b','Bread',15,10],['c','Eggs (18)',61.99,50],['d','Milk: N$ 19.95',22,50]]), after);
 ck('banner gone', !/price written in the name/.test(await p.innerText('#content')));
 const tile=await p.$eval('[data-add="a"]',e=>e.innerText.replace(/\s+/g,' ')); ck('tile shows name and green price', /Polana Maize Meal \(3kg\)/.test(tile) && /79\.99/.test(tile) && !/N\$ 79\.99.*N\$/.test(tile), tile);
 ck('no page errors', errs.length===0, errs);
 await b.close(); console.log(fail?'FAILED '+fail:'ALL OK'); process.exit(fail?1:0);
})();
