const { chromium } = require('playwright');
let fail=0; const ck=(n,c)=>{ console.log((c?'  ok   ':'  FAIL ')+n); if(!c){fail++;} };
(async()=>{ const b=await chromium.launch(); const ctx=await b.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}); const p=await ctx.newPage(); const errs=[]; p.on('pageerror',e=>errs.push(e.message));
 await require('./biz_boot.js')(p,{demo:true,simple:true});
 const rows = ()=>p.evaluate(()=>{ const d=document.createElement('div'); d.innerHTML=window.__t.menuRowsHtml(); return [...d.querySelectorAll('[data-drawer-row]')].map(e=>e.getAttribute('data-drawer-row')); });
 let r = await rows();
 ck('simple view shows with only the everyday pages', r.indexOf('tab-sell')>-1 && r.indexOf('tab-stock')>-1 && r.indexOf('tab-credit')>-1 && r.indexOf('stocktake')<0 && r.indexOf('pos')<0 && r.length<=12);
 ck('a Show all features row is offered', await p.evaluate(()=>/Show all features/.test(window.__t.menuRowsHtml())));
 ck('the setting is saved on', await p.evaluate(()=>window.__t.State.settings.simpleMode===true));
 await p.evaluate(()=>window.__t.setTab('reports')); await p.waitForTimeout(200);
 ck('hidden pages are still reachable', await p.evaluate(()=>window.__t.State.tab==='reports'));
 await p.evaluate(()=>window.__t.vSimpleToggle()); await p.waitForTimeout(300);
 r = await rows(); ck('Show all features brings the full menu back', r.indexOf('stocktake')>-1 && r.indexOf('terminal')>-1 && r.length>20);
 ck('and offers Simple view again', await p.evaluate(()=>/Simple view/.test(window.__t.menuRowsHtml())));
 await p.evaluate(()=>window.__t.btSave({simpleMode:undefined})); r = await rows();
 ck('a shop with no choice saved keeps the full menu', r.indexOf('stocktake')>-1);
 ck('no page errors', errs.length===0); if(errs.length) console.log(errs.slice(0,3));
 await b.close(); console.log(fail?'FAILED '+fail:'ALL OK'); process.exit(fail?1:0);
})();
