const { chromium } = require('playwright');
let fail=0; const ck=(n,c)=>{ console.log((c?'  ok   ':'  FAIL ')+n); if(!c){fail++;} };
(async()=>{ const b=await chromium.launch();
 const ctx=await b.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}); await ctx.addInitScript(()=>{ window.__forceSimple=true; });
 const p=await ctx.newPage(); const errs=[]; p.on('pageerror',e=>errs.push(e.message));
 await require('./biz_boot.js')(p,{demo:true});
 const rows = ()=>p.evaluate(()=>{ const d=document.createElement('div'); d.innerHTML=window.__t.menuRowsHtml(); return [...d.querySelectorAll('[data-drawer-row]')].map(e=>e.getAttribute('data-drawer-row')); });
 await p.evaluate(()=>{ window.__t.setTab('dashboard'); window.__t.render(); }); await p.waitForTimeout(300);
 let r = await rows();
 ck('every retail owner gets the short menu', r.indexOf('tab-sell')>-1 && r.indexOf('tab-stock')>-1 && r.indexOf('tab-credit')>-1 && r.indexOf('stocktake')<0 && r.indexOf('pos')<0 && r.indexOf('terminal')<0 && r.length<=10);
 ck('there is no Show all features row for them', await p.evaluate(()=>!/Show all features|Simple view/.test(window.__t.menuRowsHtml())) && await p.evaluate(()=>!/Show all features/.test(document.body.innerText)));
 const dash = await p.evaluate(()=>document.body.innerText);
 ck('the simple dashboard shows today, a big Sell button and three numbers', /today.s sales/i.test(dash) && await p.evaluate(()=>!!document.querySelector('[data-vq="sell"].btn-primary')) && /cash sales today/i.test(dash) && /low stock/i.test(dash) && /customers owe you/i.test(dash));
 ck('it does not show the long list of retail tiles', await p.evaluate(()=>!/Pesa Smart Tools|Business tools/.test(document.body.innerText)));
 ck('the Developer panel is also a row in the menu', (await rows()).indexOf('v-dev')>-1);
 ck('a Developer panel link is on the dashboard', await p.evaluate(()=>!!document.querySelector('[data-vq="dev"]')));
 // developer panel with a throw away test login (the real login is made with tools/make_dev_hash.mjs and is never in the repo)
 await p.click('[data-vq="dev"]'); await p.waitForSelector('#dvGo');
 ck('the panel is titled Developer panel and asks for username and password', await p.evaluate(()=>/Developer panel/.test(document.querySelector('.sheet').innerText) && !!document.getElementById('dvU') && document.getElementById('dvP').type==='password'));
 await p.fill('#dvU','dev@example.com'); await p.fill('#dvP','whatever-12345'); await p.click('#dvGo'); await p.waitForFunction(()=>document.getElementById('dvE').textContent.length>0);
 ck('with no master login set, nobody can get in', await p.evaluate(()=>/Wrong username or password/.test(document.getElementById('dvE').textContent) && !window.__t.devUnlocked()));
 await p.evaluate(async()=>{ const salt='00112233445566778899aabbccddeeff'; window.__t.setDev({ salt:salt, hash:await window.__t.devDerive('Dev@Example.com','correct-horse-9','' + salt) }); });
 await p.fill('#dvP','wrong-password'); await p.click('#dvGo'); await p.waitForFunction(()=>/Wrong/.test(document.getElementById('dvE').textContent));
 ck('a wrong password is refused', await p.evaluate(()=>!window.__t.devUnlocked()));
 await p.fill('#dvU','dev@example.com'); await p.fill('#dvP','correct-horse-9'); await p.click('#dvGo'); await p.waitForFunction(()=>window.__t.devUnlocked(),null,{timeout:8000});
 await p.waitForTimeout(500);
 r = await rows(); ck('the right login unlocks the full app (username not case sensitive)', r.indexOf('stocktake')>-1 && r.indexOf('terminal')>-1 && r.indexOf('v-dev')>-1 && r.length>20);
 // give someone else access
 await p.evaluate(()=>window.__t.openDevPanel()); await p.waitForSelector('#dvAdd');
 await p.fill('#dvN','Helper'); await p.fill('#dvNU','helper@example.com'); await p.fill('#dvNP','short'); await p.click('#dvAdd');
 ck('a short password for a helper is refused', await p.evaluate(()=>/at least 10/.test(document.getElementById('dvNE').textContent)));
 await p.fill('#dvNP','helper-pass-2026'); await p.click('#dvAdd'); await p.waitForFunction(()=>(window.__t.State.settings.devAccess||[]).length===1);
 ck('access is stored as a salted hash, never the password', await p.evaluate(()=>{ const x=window.__t.State.settings.devAccess[0]; return /^[0-9a-f]{64}$/.test(x.hash) && x.salt.length===32 && !JSON.stringify(x).includes('helper-pass') && !JSON.stringify(x).includes('helper@example.com'); }));
 await p.waitForSelector('#dvLock'); await p.click('#dvLock'); await p.waitForTimeout(400);
 ck('Lock goes back to the simple dashboard', await p.evaluate(()=>!window.__t.devUnlocked()) && (await rows()).indexOf('stocktake')<0);
 await p.evaluate(()=>window.__t.openDevPanel()); await p.waitForSelector('#dvGo');
 await p.fill('#dvU','helper@example.com'); await p.fill('#dvP','helper-pass-2026'); await p.click('#dvGo'); await p.waitForFunction(()=>window.__t.devUnlocked(),null,{timeout:8000});
 ck('the person given access can unlock', await p.evaluate(()=>window.__t.devUnlocked()));
 await p.evaluate(()=>window.__t.openDevPanel()); await p.waitForSelector('#dvLock');
 ck('but only the developer manages the access list', await p.evaluate(()=>!document.getElementById('dvAdd')));
 await p.click('#dvLock'); await p.waitForTimeout(300);
 // lock out after 5 wrong tries
 await p.evaluate(()=>window.__t.openDevPanel()); await p.waitForSelector('#dvGo');
 for(let i=0;i<5;i++){ await p.fill('#dvU','x@example.com'); await p.fill('#dvP','bad-password-'+i); await p.click('#dvGo'); await p.waitForFunction(()=>!document.getElementById('dvGo').disabled && document.getElementById('dvE').textContent.length>0); }
 await p.fill('#dvU','dev@example.com'); await p.fill('#dvP','correct-horse-9'); await p.click('#dvGo'); await p.waitForFunction(()=>/Too many tries/.test(document.getElementById('dvE').textContent));
 ck('five wrong tries lock the panel for a while, even for the right password', await p.evaluate(()=>!window.__t.devUnlocked()));
 // an empty new shop
 const ctx2 = await b.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}); await ctx2.addInitScript(()=>{ window.__forceSimple=true; });
 const p2 = await ctx2.newPage(); const errs2=[]; p2.on('pageerror',e=>errs2.push(e.message));
 await require('./biz_boot.js')(p2); await p2.evaluate(()=>{ window.__t.setTab('dashboard'); window.__t.render(); }); await p2.waitForTimeout(400);
 ck('an empty shop sees Get started with two steps', await p2.evaluate(()=>/get started in two steps/i.test(document.body.innerText) && /Add 3 products/.test(document.body.innerText)));
 ck('the long setup guide does not pop up by itself', await p2.evaluate(()=>new Promise(r=>setTimeout(()=>r(!/Setup guide/.test(document.body.innerText)),2600))));
 await p2.click('[data-vq="quickadd"]'); await p2.waitForSelector('#qaSave');
 await p2.click('#qaSave'); ck('an empty form is refused', await p2.evaluate(()=>window.__t.State.products.length===0));
 await p2.fill('[data-qa="n0"]','Bread loaf'); await p2.fill('[data-qa="p0"]','13'); await p2.fill('[data-qa="q0"]','20');
 await p2.fill('[data-qa="n1"]','Cold drink'); await p2.fill('[data-qa="p1"]','12'); await p2.fill('[data-qa="q1"]','0');
 await p2.fill('[data-qa="n2"]','Airtime'); await p2.fill('[data-qa="p2"]','10');
 await p2.click('#qaSave'); await p2.waitForFunction(()=>window.__t.State.products.length===3,null,{timeout:5000}).catch(()=>{});
 ck('three products are saved with price and stock', await p2.evaluate(()=>{ const a=window.__t.State.products; return a.length===3 && a.find(x=>x.name==='Bread loaf').sellPrice===13 && a.find(x=>x.name==='Bread loaf').stockQty===20 && a.find(x=>x.name==='Airtime').stockQty===0; }));
 await p2.waitForTimeout(300);
 ck('the first step is ticked', await p2.evaluate(()=>/✓ Add 3 products/.test(document.body.innerText)));
 ck('no page errors', errs.length===0 && errs2.length===0); if(errs.length||errs2.length) console.log(errs.slice(0,3), errs2.slice(0,3));
 await b.close(); console.log(fail?'FAILED '+fail:'ALL OK'); process.exit(fail?1:0);
})();
