/* Ashelz Guide: an offline assistant. No server and no AI service: it understands what you type with rules and
   searches the built-in knowledge base (knowledge.js). It returns {text, verses, chips, actions}; app.js shows it
   and runs the actions. It is not a general chatbot and it is not a counselor, and it says so when it matters. */
(function(root){
  var KB = root.KB || { books: {}, topics: [], skills: [], qa: [], facts: {} };
  var mem = { topic: null, vi: 0, last: null };
  var ACC = { blue: '#1B6EF3', 'royal blue': '#1B6EF3', gold: '#F5B52E', yellow: '#F5B52E', red: '#D8343F', 'ribbon red': '#D8343F', sky: '#4FA8F0', 'sky blue': '#4FA8F0' };
  var PAGES = { home: 'home', dashboard: 'home', bible: 'bible', devotion: 'devotions', devotions: 'devotions', devotional: 'devotions', counseling: 'counsel', counselling: 'counsel', counsel: 'counsel', hope: 'hope', 'messages of hope': 'hope', prayer: 'prayers', prayers: 'prayers', notes: 'notes', note: 'notes', settings: 'settings', theme: 'theme', appearance: 'theme', account: 'account', notifications: 'notifications', reminders: 'notifications', backup: 'data', translations: 'translations', translation: 'translations', about: 'about', more: 'more' };
  function norm(s){ return (s || '').toLowerCase().replace(/[’']/g, "'").replace(/[^a-z0-9:' ]+/g, ' ').replace(/\s+/g, ' ').trim(); }
  function has(t, list){ for(var i = 0; i < list.length; i++){ if(new RegExp('(^| )' + list[i] + '( |$)').test(t)) return true; } return false; }
  function pick(a){ return a[Math.floor(Math.random() * a.length)]; }
  var bookNames = Object.keys(KB.books);
  function findBook(t){ var best = null; bookNames.forEach(function(b){ var n = b.toLowerCase(); if(new RegExp('(^| )' + n.replace(/ /g, ' ') + '( |$)').test(t) || (n === 'psalms' && /(^| )psalm( |$)/.test(t)) || (n === 'song of solomon' && /song of songs/.test(t))){ if(!best || b.length > best.length) best = b; } }); return best; }
  function parseRef(t){ var m = /((?:[123] ?)?[a-z]+(?: of [a-z]+)?)\s+(\d{1,3})(?::(\d{1,3}))?/.exec(t); if(!m) return null; var b = findBook(m[1].replace(/^(\d) /, '$1 ')) || findBook(m[1]); if(!b) return null; return { book: b, ch: +m[2], verse: m[3] ? +m[3] : null }; }
  function stem(w){ return w.replace(/(ing|ed|es|s|e|ness|ful)$/, ''); }
  function mentions(t, w){ if(new RegExp('(^| )' + w + '( |$)').test(t)) return true; if(w.length < 5) return false; var sw = stem(w); return sw.length >= 4 && t.split(' ').some(function(k){ return k.length >= 5 && stem(k) === sw; }); }
  function scoreTopic(t, tp){ var s = 0, ws = tp.words.split(' '); ws.forEach(function(w){ if(w && mentions(t, w)) s += w.length > 4 ? 2 : 1; }); (tp.title.toLowerCase().split(/[^a-z]+/)).forEach(function(w){ if(w.length > 3 && t.indexOf(w) > -1) s += 1; }); return s; }
  function bestTopic(t){ var b = null, bs = 0; KB.topics.forEach(function(tp){ var s = scoreTopic(t, tp); if(s > bs){ bs = s; b = tp; } }); bestTopic.score = bs; return bs >= 1 ? b : null; }
  function topicReply(tp, name){ mem.topic = tp; mem.vi = 1; var v = tp.verses[0]; mem.last = { ref: v.ref, text: v.text };
    return { text: tp.intro + '\n\nHere is a verse to hold on to:', verses: [v], chips: ['Another verse', 'What can I do?', 'Pray for me', 'Save that'] }; }
  function crisis(t){ return /(kill myself|end my life|take my own life|suicid|want to die|wanna die|better off dead|no reason to live|hurt myself|harm myself|cut myself|self harm|selfharm|end it all)/.test(t); }
  function abuse(t){ return /(abusing me|abuses me|beats me|hits me|being abused|raped|molest|unsafe at home|afraid of my (husband|wife|partner|father|boyfriend))/.test(t); }
  function reply(input, env){ env = env || {}; var raw = (input || '').trim(), t = norm(raw), name = env.name || '';
    if(!t) return { text: 'I am here. Tell me what is on your heart, or ask me for a verse, a prayer, or to open any part of the app.' };
    if(crisis(t)) return { text: 'I am really glad you told me. Your life matters, and you do not have to carry this alone. Please reach out right now: call your local emergency number or go to the nearest clinic or hospital, and tell someone you trust (a family member, a pastor, a friend) to stay with you. If you can, put distance between you and anything you could use to hurt yourself.\n\nI am an app, not a person or a professional, so I cannot keep you safe the way they can. But here is a truth for this moment:', verses: [{ ref: 'Psalm 34:18', text: 'The LORD is nigh unto them that are of a broken heart; and saveth such as be of a contrite spirit.' }], chips: ['Pray for me', 'I feel hopeless'], safety: true };
    if(abuse(t)) return { text: 'I am so sorry. What you describe is not your fault, and you deserve to be safe. Please contact your local emergency services or police, or go somewhere safe such as a clinic, a church or a trusted family member. Tell someone you trust what is happening. Faith is not a reason to stay in danger.', verses: [{ ref: 'Psalm 46:1', text: 'God is our refuge and strength, a very present help in trouble.' }], safety: true };
    /* follow ups about the last answer */
    if(/^(another|another one|another verse|more|next|next verse|one more|again|more verses|show more)$/.test(t) && mem.topic){ var tp = mem.topic; var v = tp.verses[mem.vi % tp.verses.length]; mem.vi++; mem.last = { ref: v.ref, text: v.text }; return { text: tp.title + ' (' + ((mem.vi - 1) % tp.verses.length + 1) + ' of ' + tp.verses.length + ')', verses: [v], chips: ['Another verse', 'Pray for me', 'What can I do?'] }; }
    if(/^(another|more|next|another verse|one more)$/.test(t)){ var all = []; KB.topics.forEach(function(x){ all = all.concat(x.verses); }); var vv = pick(all); mem.last = { ref: vv.ref, text: vv.text }; return { text: 'Here is a verse for you:', verses: [vv], chips: ['Another verse', 'Share that', 'Save that'] }; }
    if(/(what can i do|what should i do|practical|any (tips|advice|steps)|how do i cope|help me cope|^tips$|^advice$)/.test(t) && mem.topic) return { text: 'Some small, practical steps for ' + mem.topic.title.toLowerCase() + ':\n\n' + mem.topic.practices.map(function(p, i){ return (i + 1) + '. ' + p; }).join('\n') + '\n\nGo gently. One small step today is enough.', chips: ['Pray for me', 'Another verse', 'Mind renewal exercise'] };
    if(/(pray for me|pray with me|say a prayer|can you pray|prayer for me|^pray$|^amen$)/.test(t)){ var tp2 = mem.topic || KB.topics.filter(function(x){ return x.id === 'peace'; })[0]; var pr = (name ? name + ', ' : '') + tp2.prayer; return { text: 'Let us pray together:\n\n' + tp2.prayer + '\n\nAmen.', chips: ['Add to My Prayers', 'Another verse'], pray: tp2.prayer }; }
    if(/^(add to my prayers|save prayer|save this prayer)$/.test(t)){ var tp3 = mem.topic; return { text: 'Saved to My Prayers.', actions: [{ type: 'addPrayer', text: tp3 ? tp3.prayer : 'Lord, be with me today. Amen.' }] }; }
    if(/^(save that|save it|save this|note that|add to notes|save to notes|keep that|bookmark that)$/.test(t)){ if(!mem.last) return { text: 'Nothing to save yet. Ask me for a verse first.' }; return { text: 'Saved to your Notes.', actions: [{ type: 'addNote', text: mem.last.ref + ' (KJV)\n' + mem.last.text }] }; }
    if(/^(share that|share it|share this|send that|share verse)$/.test(t)){ if(!mem.last) return { text: 'Nothing to share yet. Ask me for a verse first.' }; return { text: 'Opening share.', actions: [{ type: 'share', text: mem.last.ref + ' (KJV)\n' + mem.last.text }] }; }
    if(/^(copy that|copy it|copy this|copy verse)$/.test(t)){ if(!mem.last) return { text: 'Nothing to copy yet. Ask me for a verse first.' }; return { text: 'Copied.', actions: [{ type: 'copy', text: mem.last.ref + ' (KJV)\n' + mem.last.text }] }; }
    /* commands */
    if(/^(help|what can you do|commands|how do you work|menu|options)$/.test(t) || /what can you (do|help)/.test(t)) return { text: 'I can talk with you and help you use the app. Try:\n• "I feel anxious" or "my marriage is hard" for scripture, steps and prayer\n• "Open John 3:16" or "go to Devotions"\n• "Today\'s verse" or "today\'s devotion"\n• "Dark mode", "gold theme", "bigger text"\n• "Add a prayer: help my family"\n• "Note: sermon on grace"\n• "Remind me at 7:30"\n• "Tell me about Romans"\n• "Explain grace" or "who is Jesus"\n• "How do I renew my mind?"\nI work offline and I am a rule based helper, not a general AI or a counselor.', chips: ['Today\'s verse', 'I feel anxious', 'Open Psalm 23', 'Dark mode'] };
    if(/(switch|turn|go|change|make).*(to )?(dark|night)( mode| theme)?$/.test(t) || /(dark mode|night mode|dark theme|go dark)/.test(t) || /^dark$/.test(t)) return { text: 'Dark mode is on.', actions: [{ type: 'theme', patch: { themeMode: 'dark' } }] };
    if(/(switch|turn|go|change|make).*(to )?(light|day)( mode| theme)?$/.test(t) || /(light mode|day mode|light theme|go light|bright mode)/.test(t) || /^light$/.test(t)) return { text: 'Light mode is on.', actions: [{ type: 'theme', patch: { themeMode: 'light' } }] };
    var ac = Object.keys(ACC).sort(function(a, b){ return b.length - a.length; }).filter(function(k){ return new RegExp('(^| )' + k + '( |$)').test(t); })[0];
    if(ac && /(theme|colou?r|accent|make it|change|switch|use)/.test(t)) return { text: 'Done: the accent colour is now ' + ac + '.', actions: [{ type: 'theme', patch: { accentColor: ACC[ac] } }] };
    if(/(bigger|larger|increase|big|large)( text| font| writing| letters)?/.test(t) && /(text|font|writing|letters|bigger|larger)/.test(t) && !/(bigger problem)/.test(t)) return { text: 'Text size is now large.', actions: [{ type: 'theme', patch: { fontSize: 'large' } }] };
    if(/(smaller|small|decrease|reduce)( text| font| writing)?/.test(t) && /(text|font|writing|smaller)/.test(t)) return { text: 'Text size is now small.', actions: [{ type: 'theme', patch: { fontSize: 'small' } }] };
    if(/(normal|medium|default|reset) (text|font|size)/.test(t)) return { text: 'Text size is back to normal.', actions: [{ type: 'theme', patch: { fontSize: 'medium' } }] };
    var m;
    if((m = /^(?:add (?:a )?prayer|pray(?:er)? request|my prayer)[: ]+(.{3,})$/.exec(raw.replace(/\s+/g, ' ')))) return { text: 'Added to My Prayers: "' + m[1] + '"', actions: [{ type: 'addPrayer', text: m[1] }] };
    if((m = /^(?:note|add (?:a )?note|write (?:a )?note|take (?:a )?note|jot)[: ]+(.{2,})$/i.exec(raw.replace(/\s+/g, ' ')))) return { text: 'Saved to Notes.', actions: [{ type: 'addNote', text: m[1] }] };
    if((m = /remind(?:er)?.*?(?:at|for)\s+(\d{1,2})(?::(\d{2}))?\s*(am|pm)?/.exec(t)) || (m = /(?:set|turn on).*reminder.*?(\d{1,2})(?::(\d{2}))?\s*(am|pm)?/.exec(t))){ var hr = +m[1], mi = +(m[2] || 0); if(m[3] === 'pm' && hr < 12) hr += 12; if(m[3] === 'am' && hr === 12) hr = 0; if(hr > 23 || mi > 59) return { text: 'That time does not look right. Try "remind me at 7:30 am".' }; var tm = ('0' + hr).slice(-2) + ':' + ('0' + mi).slice(-2); return { text: 'Done. Your daily reminder is set for ' + tm + '. It shows while the app is open or installed on your phone.', actions: [{ type: 'remind', on: true, time: tm }] }; }
    if(/(turn off|stop|disable|cancel).*(reminder|notification)/.test(t)) return { text: 'The daily reminder is off.', actions: [{ type: 'remind', on: false }] };
    if((m = /(?:my name is|call me|i am called|i'm called)\s+([a-z][a-z' -]{1,30})$/i.exec(raw.trim()))){ var nm = m[1].replace(/\b\w/g, function(c){ return c.toUpperCase(); }).trim(); return { text: 'Lovely to meet you, ' + nm + '. I will use your name in your greeting.', actions: [{ type: 'setName', name: nm }] }; }
    if(/(today'?s|todays|daily) (verse|scripture)|verse of the day|verse for today/.test(t)){ var tv = env.today && env.today(); if(tv){ mem.last = { ref: tv.ref, text: tv.text }; return { text: 'Today\'s verse:', verses: [{ ref: tv.ref, text: tv.text }], chips: ['Today\'s devotion', 'Save that', 'Share that'] }; } }
    if(/(today'?s|todays|daily) (devotion|devotional)|^devotion$/.test(t)) return { text: 'Opening today\'s devotion.', actions: [{ type: 'go', id: 'devotions' }] };
    if(/(today'?s|todays|daily) prayer/.test(t)){ var tp4 = env.prayer && env.prayer(); if(tp4) return { text: tp4 + '\n\nAmen.', chips: ['Add to My Prayers'], pray: tp4 }; }
    if(/random verse|surprise me|give me a verse|^verse$|a verse for me/.test(t)){ var all2 = []; KB.topics.forEach(function(x){ all2 = all2.concat(x.verses); }); var rv = pick(all2); mem.last = { ref: rv.ref, text: rv.text }; return { text: 'Here is a verse for you:', verses: [rv], chips: ['Another verse', 'Save that', 'Share that'] }; }
    /* open a reference */
    if(/(^| )(open|read|show|go to|take me to|find|look up|turn to|display)( |$)|^[1-3a-z ]+ \d+(:\d+)?$/.test(t)){ var r = parseRef(t); if(r) return { text: 'Opening ' + r.book + ' ' + r.ch + (r.verse ? ':' + r.verse : '') + '.', actions: [{ type: 'reader', book: r.book, ch: r.ch, verse: r.verse }] }; }
    var pg = /(open|go to|show|take me to|switch to|visit|^)\s*(?:the )?([a-z ]+?)(?: page| section| screen| tab)?$/.exec(t.replace(/^(please|can you|could you|pls)\s+/, ''));
    if(pg && /(open|go to|take me|show me|switch to|visit)/.test(t)){ var key = pg[2].trim(); if(PAGES[key]) return { text: 'Opening ' + key + '.', actions: [{ type: 'go', id: PAGES[key] }] }; var bk = findBook(key); if(bk) return { text: 'Opening ' + bk + '.', actions: [{ type: 'go', id: 'chapters', arg: bk }] }; }
    if(/(^| )(switch|change|use|set) .*(translation|version)|(^| )(read|open) .* in (kjv|web|bbe|asv|oeb|almeida|cherokee|clementine|rccv)/.test(t)) return { text: 'Opening Translations, where you can pick a version and language.', actions: [{ type: 'go', id: 'translations' }] };
    if(/(clear|delete|erase|reset) (the )?(chat|conversation|history)/.test(t)) return { text: 'Chat cleared.', actions: [{ type: 'clear' }] };
    /* small talk */
    if(/^(hi|hello|hey|hallo|howzit|hiya|good (morning|afternoon|evening)|greetings|sup|yo)( there| guide| ashelz)?$/.test(t)) return { text: pick(['Hello' + (name ? ', ' + name : '') + '! How is your heart today?', 'Hi' + (name ? ' ' + name : '') + '. It is good to see you. What is on your mind?', 'Peace to you' + (name ? ', ' + name : '') + '. How can I help?']), chips: ['I feel anxious', 'Today\'s verse', 'Pray for me', 'What can you do?'] };
    if(/how are you|how are u|how is it going|how's it going|how do you do|you okay/.test(t)) return { text: 'I am well, thank you for asking. I am an app, so I do not have feelings the way you do, but I enjoy helping. How are you really doing today?', chips: ['I am good', 'Not so good', 'Pray for me'] };
    if(/^(i am good|im good|i'm good|i am fine|im fine|fine|good|great|i am great|doing well|all good|i'm well|i am well)( thanks| thank you)?$/.test(t)) return { text: 'I am glad to hear it. Let us thank God for the good days. Would you like a verse of gratitude or to see today\'s devotion?', chips: ['Gratitude', 'Today\'s devotion'] };
    if(/^(not so good|not good|not great|bad|terrible|awful|i am not ok|i'm not ok|not okay|not ok|so so|meh|tired|sad)$/.test(t)) return { text: 'I am sorry it is heavy right now. You do not have to pretend with me. Would you like to tell me what is going on, or would a verse and a short prayer help?', chips: ['I feel anxious', 'I feel sad', 'Pray for me'] };
    if(/^(thanks|thank you|thx|ty|cheers|appreciate it|thanks a lot|thank you so much)( guide)?$/.test(t)) return { text: pick(['You are most welcome. God bless you.', 'Any time. I am here whenever you need me.', 'Glad to help. Go well.']) };
    if(/^(bye|goodbye|good night|goodnight|see you|later|cya|farewell)( guide)?$/.test(t)) return { text: 'Goodbye' + (name ? ', ' + name : '') + '. The Lord bless you and keep you. Come back any time.' };
    if(/who are you|what are you|your name|are you (a )?(bot|robot|ai|human|real)/.test(t)) return { text: 'I am the Ashelz Guide, the built-in helper of the Ashelz Bible App. I am a computer program that runs on your phone without internet or any outside AI service. I know the Bible\'s books, themes and a library of verses, prayers and biblical coping skills, and I can run the app for you. I am not a person, a pastor or a counselor.' };
    if(/(who (made|created|built|developed|founded|designed) (you|this|the app|ashelz))|your (maker|creator|developer|founder)/.test(t)) return { text: 'The Ashelz Bible App was founded and developed by Loren Ashyn Van Rensburg, dedicated to making the Word available to everyone, everywhere, entirely for free.' };
    if(/(is (this|it|the)( app)? free|how much|price|cost|subscription|do i have to pay|ads)/.test(t)) return { text: 'The app is 100% free: no payments, no subscriptions, no ads, no locked features.' };
    if(/(tell me a joke|joke)/.test(t)) return { text: pick(['Why could Jonah not trust the ocean? There was something fishy about it.', 'What did Adam say the day before Christmas? It is Christmas, Eve!']) };
    if(/i love you|you are (great|amazing|awesome|nice|kind|helpful|good)/.test(t)) return { text: 'That is kind of you. God loves you far more than I can say, and I am glad to be of help.' };
    if(/(i am|im|i'm) (bored|lost)/.test(t)) return { text: 'Let us do something good with the moment. I can open a chapter, give you a verse or help you write a prayer.', chips: ['Today\'s verse', 'Open Psalm 23', 'Pray for me'] };
    /* book summaries and chapter counts */
    var bk2 = findBook(t);
    if(bk2 && /(tell me about|about|summary|summar|overview|what is|what's|explain|theme|book of|what happens)/.test(t) && !parseRef(t)){ var bi = KB.books[bk2]; return { text: bk2 + ': ' + bi[0] + '\n\n' + bi[1], chips: ['Open ' + bk2, 'Today\'s verse'], actions: [] }; }
    if(/how many (books|chapters|verses)/.test(t)) return { text: 'The Bible has 66 books: 39 in the Old Testament and 27 in the New. The longest chapter is Psalm 119 and the shortest is Psalm 117.' };
    /* skills (psychology tied to Scripture) */
    var sk = KB.skills.filter(function(s){ return new RegExp('(^| )(' + s.id + '|' + s.title.toLowerCase().split(/[^a-z]+/).filter(function(w){ return w.length > 4; }).join('|') + ')').test(t); })[0];
    if(/(exercise|technique|skill|coping|renew my mind|renew the mind|negative thoughts|overthink|breathing|grounding|calm down|panic attack|mindful)/.test(t) || sk){
      var s2 = sk || (/breath|panic|calm/.test(t) ? KB.skills.filter(function(s){ return s.id === 'breathe'; })[0] : /ground|panic/.test(t) ? KB.skills.filter(function(s){ return s.id === 'ground'; })[0] : /think|negative|overthink|renew|mind/.test(t) ? KB.skills.filter(function(s){ return s.id === 'renew'; })[0] : KB.skills[Math.floor(Math.random() * KB.skills.length)]);
      if(s2){ mem.last = { ref: s2.verse.ref, text: s2.verse.text }; return { text: s2.title + '\n\n' + s2.how + '\n\nScripture to pair with it:', verses: [s2.verse], chips: ['Another exercise', 'Pray for me', 'I feel anxious'] }; } }
    if(/^another exercise$/.test(t)){ var s3 = pick(KB.skills); mem.last = { ref: s3.verse.ref, text: s3.verse.text }; return { text: s3.title + '\n\n' + s3.how, verses: [s3.verse], chips: ['Another exercise', 'Pray for me'] }; }
    /* faith questions */
    var tq = t.replace(/(what|how) (does|do) (the )?(bible|scripture|god|jesus) (say|says|speak|teach)( about| on)?/, ' '), qb = null, qs = 0; KB.qa.forEach(function(q){ var s = 0; q.words.split(' ').forEach(function(w){ if(w.length > 2 && mentions(tq, w)) s += w.length > 4 ? 2 : 1; }); if(tq.indexOf(q.q) > -1) s += 4; if(s > qs){ qs = s; qb = q; } });
    var tpPre = bestTopic(t), tpScore = bestTopic.score || 0;
    if(qb && qs >= 3 && qs > tpScore) return { text: qb.a, chips: ['Another question', 'Today\'s verse'] };
    /* verse search by topic */
    var tpc = tpPre;
    if(tpc) { if(/(verse|scripture|bible say|says the bible|what does the bible)/.test(t) || true) return topicReply(tpc, name); }
    /* search every stored verse for the user's words */
    var words = t.split(' ').filter(function(w){ return w.length > 3 && !/^(that|this|with|have|what|about|from|your|please|would|could|there|they|them|then|when|will|just|like|know|tell|give|want|need|help|feel|does|said|says)$/.test(w); }), hit = null, hs = 0;
    KB.topics.forEach(function(x){ x.verses.forEach(function(v){ var s = 0, vt = v.text.toLowerCase(); words.forEach(function(w){ if(vt.indexOf(w) > -1) s++; }); if(s > hs){ hs = s; hit = v; } }); });
    if(hit && hs >= 1 && words.length){ mem.last = { ref: hit.ref, text: hit.text }; return { text: 'This verse speaks to what you said:', verses: [hit], chips: ['Another verse', 'Pray for me', 'Save that'] }; }
    /* feelings: reflective listening */
    if(/(^| )(i feel|i am feeling|i'm feeling|im feeling|i have been feeling|i've been feeling)( |$)/.test(t)) return { text: 'Thank you for telling me. What you feel is real, and it matters to God. Can you tell me a little more: is it about your family, your health, money, work, or your heart before God? Or I can simply share a verse and pray with you.', chips: ['Pray for me', 'Today\'s verse', 'I feel anxious', 'I feel lonely'] };
    return { text: 'I am not sure I understood that, and I would rather say so than guess. You can tell me how you feel ("I am anxious", "my marriage is struggling"), ask for a verse or a prayer, ask about a book or a belief ("who is Jesus"), or tell me to open something ("Open John 3"). Type "help" for more.', chips: ['Help', 'Today\'s verse', 'Pray for me', 'I feel anxious'] };
  }
  root.Guide = { reply: reply, reset: function(){ mem.topic = null; mem.vi = 0; mem.last = null; }, memory: mem };
  if(typeof module !== 'undefined') module.exports = root.Guide;
})(typeof window !== 'undefined' ? window : global);
