/* Gospel music for the devotion page. Hymns are in the public domain: their opening words are shown here and "Listen" opens a YouTube search.
   Modern gospel songs are only listed by title and artist (the words are copyrighted), with a YouTube search link. No audio is stored in the app. */
window.MUSIC = {
  hymns: {
    amazing: { t: 'Amazing Grace', by: 'John Newton, 1779', ref: 'Ephesians 2:8', l: 'Amazing grace! how sweet the sound,\nThat saved a wretch like me!\nI once was lost, but now am found;\nWas blind, but now I see.' },
    itiswell: { t: 'It Is Well with My Soul', by: 'Horatio Spafford, 1873', ref: 'Isaiah 48:18', l: 'When peace like a river attendeth my way,\nWhen sorrows like sea billows roll;\nWhatever my lot, Thou hast taught me to say,\nIt is well, it is well with my soul.' },
    besttill: { t: 'Be Still, My Soul', by: 'Katharina von Schlegel, tr. Jane Borthwick', ref: 'Psalm 46:10', l: 'Be still, my soul: the Lord is on thy side;\nBear patiently the cross of grief or pain;\nLeave to thy God to order and provide;\nIn every change He faithful will remain.' },
    greatfaith: { t: 'Great Is Thy Faithfulness', by: 'Thomas Chisholm, 1923', ref: 'Lamentations 3:22-23', l: 'Great is Thy faithfulness, O God my Father,\nThere is no shadow of turning with Thee;\nThou changest not, Thy compassions, they fail not;\nAs Thou hast been, Thou forever wilt be.' },
    blessedass: { t: 'Blessed Assurance', by: 'Fanny Crosby, 1873', ref: 'Hebrews 10:22', l: 'Blessed assurance, Jesus is mine!\nO what a foretaste of glory divine!\nHeir of salvation, purchase of God,\nBorn of His Spirit, washed in His blood.' },
    whatfriend: { t: 'What a Friend We Have in Jesus', by: 'Joseph Scriven, 1855', ref: 'Philippians 4:6', l: 'What a friend we have in Jesus,\nAll our sins and griefs to bear!\nWhat a privilege to carry\nEverything to God in prayer!' },
    justasiam: { t: 'Just As I Am', by: 'Charlotte Elliott, 1835', ref: 'John 6:37', l: 'Just as I am, without one plea,\nBut that Thy blood was shed for me,\nAnd that Thou bidd\'st me come to Thee,\nO Lamb of God, I come, I come!' },
    abide: { t: 'Abide with Me', by: 'Henry Francis Lyte, 1847', ref: 'Luke 24:29', l: 'Abide with me; fast falls the eventide;\nThe darkness deepens; Lord, with me abide!\nWhen other helpers fail and comforts flee,\nHelp of the helpless, O abide with me.' },
    rock: { t: 'Rock of Ages', by: 'Augustus Toplady, 1776', ref: 'Isaiah 26:4', l: 'Rock of Ages, cleft for me,\nLet me hide myself in Thee;\nLet the water and the blood,\nFrom Thy wounded side which flowed,\nBe of sin the double cure,\nSave from wrath and make me pure.' },
    myhope: { t: 'My Hope Is Built on Nothing Less', by: 'Edward Mote, 1834', ref: 'Matthew 7:24-27', l: 'My hope is built on nothing less\nThan Jesus\' blood and righteousness;\nI dare not trust the sweetest frame,\nBut wholly lean on Jesus\' name.\nOn Christ, the solid Rock, I stand;\nAll other ground is sinking sand.' },
    fountain: { t: 'Come, Thou Fount of Every Blessing', by: 'Robert Robinson, 1758', ref: '1 Samuel 7:12', l: 'Come, Thou Fount of every blessing,\nTune my heart to sing Thy grace;\nStreams of mercy, never ceasing,\nCall for songs of loudest praise.' },
    fortress: { t: 'A Mighty Fortress Is Our God', by: 'Martin Luther, 1529', ref: 'Psalm 46:1', l: 'A mighty fortress is our God,\nA bulwark never failing;\nOur helper He amid the flood\nOf mortal ills prevailing.' },
    olove: { t: 'O Love That Wilt Not Let Me Go', by: 'George Matheson, 1882', ref: 'Romans 8:38-39', l: 'O Love that wilt not let me go,\nI rest my weary soul in Thee;\nI give Thee back the life I owe,\nThat in Thine ocean depths its flow\nMay richer, fuller be.' },
    takemylife: { t: 'Take My Life, and Let It Be', by: 'Frances Havergal, 1874', ref: 'Romans 12:1', l: 'Take my life, and let it be\nConsecrated, Lord, to Thee;\nTake my moments and my days,\nLet them flow in ceaseless praise.' },
    leaning: { t: 'Leaning on the Everlasting Arms', by: 'Elisha Hoffman, 1887', ref: 'Deuteronomy 33:27', l: 'What a fellowship, what a joy divine,\nLeaning on the everlasting arms;\nWhat a blessedness, what a peace is mine,\nLeaning on the everlasting arms.' },
    trustobey: { t: 'Trust and Obey', by: 'John Sammis, 1887', ref: 'John 14:15', l: 'When we walk with the Lord\nIn the light of His Word,\nWhat a glory He sheds on our way!\nWhile we do His good will,\nHe abides with us still,\nAnd with all who will trust and obey.' },
    standing: { t: 'Standing on the Promises', by: 'Russell Carter, 1886', ref: '2 Peter 1:4', l: 'Standing on the promises of Christ my King,\nThrough eternal ages let His praises ring;\nGlory in the highest, I will shout and sing,\nStanding on the promises of God.' },
    leadeth: { t: 'He Leadeth Me', by: 'Joseph Gilmore, 1862', ref: 'Psalm 23:2', l: 'He leadeth me, O blessed thought!\nO words with heav\'nly comfort fraught!\nWhate\'er I do, where\'er I be,\nStill \'tis God\'s hand that leadeth me.' },
    jesusloves: { t: 'Jesus Loves Me', by: 'Anna Warner, 1860', ref: 'Mark 10:14', l: 'Jesus loves me! this I know,\nFor the Bible tells me so;\nLittle ones to Him belong;\nThey are weak, but He is strong.' },
    joyful: { t: 'Joyful, Joyful, We Adore Thee', by: 'Henry van Dyke, 1907', ref: 'Psalm 100:1-2', l: 'Joyful, joyful, we adore Thee,\nGod of glory, Lord of love;\nHearts unfold like flowers before Thee,\nOpening to the sun above.' },
    countbless: { t: 'Count Your Blessings', by: 'Johnson Oatman Jr., 1897', ref: 'Psalm 103:2', l: 'When upon life\'s billows you are tempest tossed,\nWhen you are discouraged, thinking all is lost,\nCount your many blessings, name them one by one,\nAnd it will surprise you what the Lord hath done.' },
    bethou: { t: 'Be Thou My Vision', by: 'Ancient Irish, tr. Eleanor Hull, 1912', ref: 'Psalm 73:25', l: 'Be Thou my Vision, O Lord of my heart;\nNaught be all else to me, save that Thou art;\nThou my best Thought, by day or by night,\nWaking or sleeping, Thy presence my light.' },
    ineed: { t: 'I Need Thee Every Hour', by: 'Annie Hawks, 1872', ref: 'John 15:5', l: 'I need Thee every hour, most gracious Lord;\nNo tender voice like Thine can peace afford.\nI need Thee, O I need Thee;\nEvery hour I need Thee;\nO bless me now, my Savior,\nI come to Thee.' },
    disconsolate: { t: 'Come, Ye Disconsolate', by: 'Thomas Moore, 1816', ref: 'Matthew 11:28', l: 'Come, ye disconsolate, where\'er ye languish,\nCome to the mercy seat, fervently kneel;\nHere bring your wounded hearts, here tell your anguish;\nEarth has no sorrow that Heav\'n cannot heal.' },
    paidall: { t: 'Jesus Paid It All', by: 'Elvina Hall, 1865', ref: 'Isaiah 1:18', l: 'I hear the Savior say,\n"Thy strength indeed is small;\nChild of weakness, watch and pray,\nFind in Me thine all in all."\nJesus paid it all,\nAll to Him I owe;\nSin had left a crimson stain,\nHe washed it white as snow.' },
    nothingblood: { t: 'Nothing but the Blood', by: 'Robert Lowry, 1876', ref: 'Hebrews 9:22', l: 'What can wash away my sin?\nNothing but the blood of Jesus;\nWhat can make me whole again?\nNothing but the blood of Jesus.' },
    sweettrust: { t: '\'Tis So Sweet to Trust in Jesus', by: 'Louisa Stead, 1882', ref: 'Psalm 56:3', l: '\'Tis so sweet to trust in Jesus,\nJust to take Him at His word;\nJust to rest upon His promise,\nJust to know, "Thus saith the Lord."' },
    river: { t: 'Like a River Glorious', by: 'Frances Havergal, 1874', ref: 'Isaiah 48:18', l: 'Like a river glorious is God\'s perfect peace,\nOver all victorious in its bright increase;\nPerfect, yet it floweth fuller every day,\nPerfect, yet it groweth deeper all the way.' },
    peaceperfect: { t: 'Peace, Perfect Peace', by: 'Edward Bickersteth, 1875', ref: 'Isaiah 26:3', l: 'Peace, perfect peace, in this dark world of sin?\nThe blood of Jesus whispers peace within.' },
    dearlord: { t: 'Dear Lord and Father of Mankind', by: 'John Greenleaf Whittier, 1872', ref: '1 Kings 19:12', l: 'Dear Lord and Father of mankind,\nForgive our foolish ways!\nRe-clothe us in our rightful mind;\nIn purer lives Thy service find,\nIn deeper reverence, praise.' },
    operfect: { t: 'O Perfect Love', by: 'Dorothy Gurney, 1883', ref: 'Mark 10:9', l: 'O perfect Love, all human thought transcending,\nLowly we kneel in prayer before Thy throne,\nThat theirs may be the love which knows no ending,\nWhom Thou for evermore dost join in one.' },
    blest: { t: 'Blest Be the Tie That Binds', by: 'John Fawcett, 1782', ref: 'Psalm 133:1', l: 'Blest be the tie that binds\nOur hearts in Christian love;\nThe fellowship of kindred minds\nIs like to that above.' },
    greatphys: { t: 'The Great Physician', by: 'William Hunter, 1880', ref: 'Mark 2:17', l: 'The great Physician now is near,\nThe sympathizing Jesus;\nHe speaks the drooping heart to cheer,\nO hear the voice of Jesus.' },
    yield: { t: 'Yield Not to Temptation', by: 'Horatio Palmer, 1868', ref: '1 Corinthians 10:13', l: 'Yield not to temptation, for yielding is sin;\nEach victory will help you some other to win;\nFight manfully onward, dark passions subdue,\nLook ever to Jesus, He\'ll carry you through.' }
  },
  /* theme of the day's verse (see tools/build_daily.js): [hymn ids], [[modern song, artist]] */
  themes: {
    anxiety: [['whatfriend', 'besttill'], [['Still', 'Hillsong Worship'], ['Goodness of God', 'Bethel Music']]],
    fear: [['fortress', 'leadeth'], [['Oceans (Where Feet May Fail)', 'Hillsong UNITED'], ['No Longer Slaves', 'Bethel Music']]],
    grief: [['itiswell', 'disconsolate'], [['Held', 'Natalie Grant'], ['Graves into Gardens', 'Elevation Worship']]],
    depression: [['disconsolate', 'abide'], [['Tell Your Heart to Beat Again', 'Danny Gokey'], ['Raise a Hallelujah', 'Bethel Music']]],
    loneliness: [['abide', 'leaning'], [['Rescue', 'Lauren Daigle'], ['Good Good Father', 'Chris Tomlin']]],
    anger: [['dearlord', 'peaceperfect'], [['Lord, I Need You', 'Matt Maher'], ['Still', 'Hillsong Worship']]],
    forgiveness: [['paidall', 'justasiam'], [['Amazing Grace (My Chains Are Gone)', 'Chris Tomlin'], ['Broken Vessels (Amazing Grace)', 'Hillsong Worship']]],
    guilt: [['nothingblood', 'paidall'], [['Broken Vessels (Amazing Grace)', 'Hillsong Worship'], ['Lord, I Need You', 'Matt Maher']]],
    marriage: [['operfect', 'blest'], [['The Blessing', 'Kari Jobe and Cody Carnes']]],
    parenting: [['jesusloves', 'blest'], [['The Blessing', 'Kari Jobe and Cody Carnes'], ['Good Good Father', 'Chris Tomlin']]],
    finance: [['greatfaith', 'countbless'], [['Jireh', 'Elevation Worship and Maverick City Music'], ['Goodness of God', 'Bethel Music']]],
    purpose: [['takemylife', 'bethou'], [['Build My Life', 'Housefires'], ['I Surrender', 'Hillsong Worship']]],
    health: [['greatphys', 'abide'], [['Raise a Hallelujah', 'Bethel Music'], ['Great Are You Lord', 'All Sons and Daughters']]],
    doubt: [['sweettrust', 'trustobey'], [['Trust in God', 'Elevation Worship'], ['Even If', 'MercyMe']]],
    temptation: [['yield', 'rock'], [['Lord, I Need You', 'Matt Maher'], ['I Surrender', 'Hillsong Worship']]],
    peace: [['river', 'peaceperfect'], [['Still', 'Hillsong Worship'], ['The Blessing', 'Kari Jobe and Cody Carnes']]],
    hope: [['myhope', 'standing'], [['Cornerstone', 'Hillsong Worship'], ['Way Maker', 'Sinach']]],
    strength: [['fortress', 'leaning'], [['Raise a Hallelujah', 'Bethel Music'], ['Great Are You Lord', 'All Sons and Daughters']]],
    identity: [['blessedass', 'jesusloves'], [['Who You Say I Am', 'Hillsong Worship'], ['You Say', 'Lauren Daigle']]],
    gratitude: [['countbless', 'joyful'], [['10,000 Reasons (Bless the Lord)', 'Matt Redman'], ['Gratitude', 'Brandon Lake']]],
    prayer: [['whatfriend', 'ineed'], [['Way Maker', 'Sinach'], ['Lord, I Need You', 'Matt Maher']]],
    love: [['olove', 'jesusloves'], [['Reckless Love', 'Cory Asbury'], ['Good Good Father', 'Chris Tomlin']]],
    patience: [['besttill', 'leadeth'], [['Do It Again', 'Elevation Worship'], ['Way Maker', 'Sinach']]],
    conflict: [['blest', 'dearlord'], [['Amazing Grace (My Chains Are Gone)', 'Chris Tomlin'], ['The Blessing', 'Kari Jobe and Cody Carnes']]],
    salvation: [['amazing', 'justasiam'], [['What a Beautiful Name', 'Hillsong Worship'], ['Mighty to Save', 'Hillsong Worship']]]
  }
};
