/* Builds ../devo.js from devo/p1.py, p2.py, p3.py: long form daily teaching. Every key scripture is looked up in the KJV files, so the verse text is exact. Stops if a reference is wrong. */
var fs = require('fs'), path = require('path'), cp = require('child_process'), root = path.join(__dirname, '..');
var line = fs.readFileSync(path.join(__dirname, 'build_deep.js'), 'utf8').split('\n').filter(function(l){ return /^var names = /.test(l); })[0];
eval(line); var cache = {};
function text(ref){ var m = /^(.+) (\d+):(\d+)(?:-(\d+))?$/.exec(ref); if(!m) throw new Error('bad ref ' + ref); var i = names.indexOf(m[1]); if(i < 0) throw new Error('bad book ' + ref); cache[i] = cache[i] || JSON.parse(fs.readFileSync(path.join(root, 'bible/kjv/' + (i + 1) + '.json'))); var ch = cache[i][+m[2] - 1], a = +m[3], z = +(m[4] || m[3]); if(!ch || !ch[z - 1]) throw new Error('missing ' + ref); return ch.slice(a - 1, z).join(' '); }
var all = {};
['p1', 'p2', 'p3'].forEach(function(f){ var j = cp.execFileSync('python3', ['-c', 'import json,sys\nexec(open(sys.argv[1]).read())\nprint(json.dumps(T))', path.join(__dirname, 'devo', f + '.py')], { maxBuffer: 1 << 26 }).toString(); var o = JSON.parse(j); Object.keys(o).forEach(function(k){ all[k] = o[k]; }); });
var out = {}, words = 0;
Object.keys(all).forEach(function(k){ var t = all[k]; out[k] = { doc: t.doc, christ: t.christ, word: t.word, walk: t.walk, scriptures: t.key.map(function(r){ return { ref: r.replace(/^Psalms /, 'Psalm '), text: text(r) }; }), prayers: t.prayers.map(function(p){ return { title: p[0], text: p[1] }; }), declare: t.declare };
  words += [].concat(t.doc, t.christ, t.word, t.walk, t.prayers.map(function(p){ return p[1]; })).join(' ').split(/\s+/).length; });
fs.writeFileSync(path.join(root, 'devo.js'), '/* Generated by tools/build_devo.js. Long form daily teaching and prayers with exact KJV scripture. */\nwindow.DEVO = ' + JSON.stringify(out) + ';\n');
console.log(Object.keys(out).length + ' themes, about ' + words + ' words, ' + Object.keys(out).reduce(function(a, k){ return a + out[k].scriptures.length; }, 0) + ' scriptures');
