#!/usr/bin/env python3
"""Rebuilds everything that shows the legal texts from docs/legal.json.
   1. the LEGAL_DOCS block inside index.html (between the LEGAL markers)
   2. the web pages in site/ (terms, privacy, refunds, support), if the site folder exists
Run from the project folder:  python3 tools/build_legal.py"""
import json, os, re, subprocess, html

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
data = json.load(open(os.path.join(root, 'docs', 'legal.json'), encoding='utf-8'))
idx_path = os.path.join(root, 'app.js')
s = open(idx_path, encoding='utf-8').read()

block = '/*LEGAL:START (generated by tools/build_legal.py from docs/legal.json, edit that file)*/\nvar LEGAL_VERSION = %s;\nvar LEGAL_DOCS = %s;\n/*LEGAL:END*/' % (
    json.dumps(data['version']), json.dumps(data['docs'], ensure_ascii=False))
s2, n = re.subn(r'/\*LEGAL:START.*?/\*LEGAL:END\*/', lambda m: block, s, flags=re.S)
if n == 0:
    raise SystemExit('markers not found in index.html')
open(idx_path, 'w', encoding='utf-8').write(s2)
print('index.html updated')

# the privacy texts live in index.html (they are also used by the consent screen and the About PDF); read them out
m = re.search(r'var PRIVACY_INTRO = (.*?);\nvar PRIVACY_SECTIONS = (\[.*?\n\]);', s2, flags=re.S)
js = 'var DEV_EMAIL="ecrypted5@gmail.com", DEV_WHATSAPP="0818211692"; var PRIVACY_INTRO=%s; var PRIVACY_SECTIONS=%s; console.log(JSON.stringify({intro:PRIVACY_INTRO,sections:PRIVACY_SECTIONS}));' % (m.group(1), m.group(2))
out = subprocess.run(['node', '-e', js], capture_output=True, text=True)
privacy = json.loads(out.stdout)
docs = dict(data['docs'])
docs['privacy'] = { 'title': 'Confidentiality and privacy', 'intro': privacy['intro'],
                    'sections': [{ 'h': x['h'], 'items': x['items'] } for x in privacy['sections']] }

site = os.path.join(root, 'site')
tpl_path = os.path.join(site, '_legal_template.html')
if os.path.isdir(site) and os.path.exists(tpl_path):
    tpl = open(tpl_path, encoding='utf-8').read()
    pages = { 'terms':'terms.html', 'privacy':'privacy.html', 'refunds':'refunds.html', 'support':'support.html' }
    for key, fn in pages.items():
        d = docs[key]
        body = '<p class="lead">%s</p>' % html.escape(d['intro'])
        for sec in d['sections']:
            body += '<h2>%s</h2><ul>%s</ul>' % (html.escape(sec['h']), ''.join('<li>%s</li>' % html.escape(i) for i in sec['items']))
        page = tpl.replace('{{TITLE}}', html.escape(d['title'])).replace('{{BODY}}', body).replace('{{UPDATED}}', html.escape(data['updated'])).replace('{{VERSION}}', html.escape(data['version']))
        open(os.path.join(site, fn), 'w', encoding='utf-8').write(page)
        print('wrote site/' + fn)
