#!/usr/bin/env python3
"""Embeds tools/intro.js into app.js between /*INTRO:START*/ and /*INTRO:END*/ marker comments.
Run again after editing tools/intro.js.   python3 tools/embed_intro.py"""
import os, re, sys
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
idx = os.path.join(ROOT, 'app.js')
src = open(idx, encoding='utf-8').read()
js = open(os.path.join(ROOT, 'tools', 'intro.js'), encoding='utf-8').read()
if '</script' in js.lower(): sys.exit('source contains </script')
block = '/*INTRO:START (generated by tools/embed_intro.py, edit tools/intro.js instead)*/\n' + js.rstrip() + '\n/*INTRO:END*/\n'
if '/*INTRO:START' in src:
    src = re.sub(r'/\*INTRO:START.*?/\*INTRO:END\*/\n', lambda m: block, src, count=1, flags=re.S)
else:
    anchor = '/*EFD:START'
    if src.count(anchor) != 1: sys.exit('anchor not found exactly once')
    src = src.replace(anchor, block + anchor, 1)
open(idx, 'w', encoding='utf-8').write(src)
print('embedded', len(block), 'bytes')
