#!/usr/bin/env python3
"""Embeds docs/efd/pesa-efd.js and tools/efd_app.js into app.js between marker comments.
Run again after editing either source file.   python3 tools/embed_efd.py"""
import os, re, sys
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
idx = os.path.join(ROOT, 'app.js')
src = open(idx, encoding='utf-8').read()
mod = open(os.path.join(ROOT, 'docs', 'efd', 'pesa-efd.js'), encoding='utf-8').read()
app = open(os.path.join(ROOT, 'tools', 'efd_app.js'), encoding='utf-8').read()
for s in (mod, app):
    if '</script' in s.lower(): sys.exit('source contains </script')
block = '/*EFD:START (generated by tools/embed_efd.py, edit docs/efd/pesa-efd.js and tools/efd_app.js instead)*/\n' + mod.rstrip() + '\n' + app.rstrip() + '\n/*EFD:END*/\n'
if '/*EFD:START' in src:
    src = re.sub(r'/\*EFD:START.*?/\*EFD:END\*/\n', lambda m: block, src, count=1, flags=re.S)
else:
    anchor = '// Show a loading state behind the auth gate until we know whether a company'
    if src.count(anchor) != 1: sys.exit('anchor not found exactly once')
    src = src.replace(anchor, block + '\n' + anchor, 1)
open(idx, 'w', encoding='utf-8').write(src)
print('embedded', len(block), 'bytes')
