#!/usr/bin/env python3
"""Embeds tools/<file> into app.js between /*<NAME>:START*/ and /*<NAME>:END*/.
Usage: python3 tools/embed_block.py NAME file.js 'anchor text (inserted before it, first time only)'
Run again after editing the source file."""
import os, re, sys
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
name, fn = sys.argv[1], sys.argv[2]
anchor = sys.argv[3] if len(sys.argv) > 3 else None
idx = os.path.join(ROOT, 'index.html' if name == 'HARDEN5' else 'app.js')   # the firewall must run first, so it lives in the page itself
src = open(idx, encoding='utf-8').read()
js = open(os.path.join(ROOT, 'tools', fn), encoding='utf-8').read()
if '</script' in js.lower(): sys.exit('source contains </script')
block = '/*%s:START (generated by tools/embed_block.py from tools/%s, edit that file instead)*/\n' % (name, fn) + js.rstrip() + '\n/*%s:END*/\n' % name
if '/*%s:START' % name in src:
    src = re.sub(r'/\*%s:START.*?/\*%s:END\*/\n' % (name, name), lambda m: block, src, count=1, flags=re.S)
else:
    if not anchor or src.count(anchor) != 1: sys.exit('anchor missing or not unique: %r count=%d' % (anchor, src.count(anchor or '')))
    src = src.replace(anchor, block + anchor, 1)
open(idx, 'w', encoding='utf-8').write(src)
print('embedded', name, len(block), 'bytes')
